const HIRAGANA_VOCAB_DATA = {
  "Vocabulary (Hiragana)": {
    "ねこ": {"romaji":["neko"],"meaning":"cat"},
    "いぬ": {"romaji":["inu"],"meaning":"dog"},
    "とり": {"romaji":["tori"],"meaning":"bird"},
    "うさぎ": {"romaji":["usagi"],"meaning":"rabbit"},
    "からす": {"romaji":["karasu"],"meaning":"crow"},
    "きつね": {"romaji":["kitsune"],"meaning":"fox"},
    "すずめ": {"romaji":["suzume"],"meaning":"sparrow"},
    "たぬき": {"romaji":["tanuki"],"meaning":"raccoon dog"},
    "ねずみ": {"romaji":["nezumi"],"meaning":"mouse"},
    "ひつじ": {"romaji":["hitsuji"],"meaning":"sheep"},
    "めだか": {"romaji":["medaka"],"meaning":"killifish"},
    "くじら": {"romaji":["kujira"],"meaning":"whale"},
    "さくら": {"romaji":["sakura"],"meaning":"cherry blossom"},
    "ひまわり": {"romaji":["himawari"],"meaning":"sunflower"},
    "あさがお": {"romaji":["asagao"],"meaning":"morning glory"},
    "もみじ": {"romaji":["momiji"],"meaning":"maple"},
    "たけのこ": {"romaji":["takenoko"],"meaning":"bamboo shoot"},
    "かみなり": {"romaji":["kaminari"],"meaning":"thunder"},
    "みずうみ": {"romaji":["mizuumi"],"meaning":"lake"},
    "あらし": {"romaji":["arashi"],"meaning":"storm"},
    "あめ": {"romaji":["ame"],"meaning":"rain"},
    "ゆき": {"romaji":["yuki"],"meaning":"snow"},
    "そら": {"romaji":["sora"],"meaning":"sky"},
    "ほし": {"romaji":["hoshi"],"meaning":"star"},
    "つき": {"romaji":["tsuki"],"meaning":"moon"},
    "やま": {"romaji":["yama"],"meaning":"mountain"},
    "かわ": {"romaji":["kawa"],"meaning":"river"},
    "うみ": {"romaji":["umi"],"meaning":"sea"},
    "はな": {"romaji":["hana"],"meaning":"flower"},
    "はる": {"romaji":["haru"],"meaning":"spring"},
    "なつ": {"romaji":["natsu"],"meaning":"summer"},
    "あき": {"romaji":["aki"],"meaning":"autumn"},
    "ふゆ": {"romaji":["fuyu"],"meaning":"winter"},
    "くも": {"romaji":["kumo"],"meaning":"cloud"},
    "かぜ": {"romaji":["kaze"],"meaning":"wind"},
    "たいよう": {"romaji":["taiyou"],"meaning":"sun"},
    "にじ": {"romaji":["niji"],"meaning":"rainbow"},
    "きり": {"romaji":["kiri"],"meaning":"fog"},
    "おにぎり": {"romaji":["onigiri"],"meaning":"rice ball"},
    "たまご": {"romaji":["tamago"],"meaning":"egg"},
    "さかな": {"romaji":["sakana"],"meaning":"fish"},
    "くだもの": {"romaji":["kudamono"],"meaning":"fruit"},
    "やさい": {"romaji":["yasai"],"meaning":"vegetable"},
    "ごはん": {"romaji":["gohan"],"meaning":"meal/rice"},
    "おちゃ": {"romaji":["ocha"],"meaning":"green tea"},
    "おかし": {"romaji":["okashi"],"meaning":"sweets"},
    "みそしる": {"romaji":["misoshiru"],"meaning":"miso soup"},
    "てんぷら": {"romaji":["tenpura"],"meaning":"tempura"},
    "さとう": {"romaji":["satou"],"meaning":"sugar"},
    "しお": {"romaji":["shio"],"meaning":"salt"},
    "わさび": {"romaji":["wasabi"],"meaning":"wasabi"},
    "あずき": {"romaji":["azuki"],"meaning":"red bean"},
    "おべんとう": {"romaji":["obentou"],"meaning":"lunch box"},
    "のみもの": {"romaji":["nomimono"],"meaning":"drink"},
    "たべもの": {"romaji":["tabemono"],"meaning":"food"},
    "おかず": {"romaji":["okazu"],"meaning":"side dish"},
    "おいしい": {"romaji":["oishii"],"meaning":"delicious"},
    "まずい": {"romaji":["mazui"],"meaning":"tastes bad"},
    "つくえ": {"romaji":["tsukue"],"meaning":"desk"},
    "ほうき": {"romaji":["houki"],"meaning":"broom"},
    "かがみ": {"romaji":["kagami"],"meaning":"mirror"},
    "とけい": {"romaji":["tokei"],"meaning":"clock/watch"},
    "めがね": {"romaji":["megane"],"meaning":"glasses"},
    "かばん": {"romaji":["kaban"],"meaning":"bag"},
    "さいふ": {"romaji":["saifu"],"meaning":"wallet"},
    "はさみ": {"romaji":["hasami"],"meaning":"scissors"},
    "ふでばこ": {"romaji":["fudebako"],"meaning":"pencil case"},
    "じしょ": {"romaji":["jisho"],"meaning":"dictionary"},
    "しんぶん": {"romaji":["shinbun"],"meaning":"newspaper"},
    "てがみ": {"romaji":["tegami"],"meaning":"letter"},
    "ふとん": {"romaji":["futon"],"meaning":"futon"},
    "まくら": {"romaji":["makura"],"meaning":"pillow"},
    "せっけん": {"romaji":["sekken"],"meaning":"soap"},
    "くつした": {"romaji":["kutsushita"],"meaning":"socks"},
    "ぼうし": {"romaji":["boushi"],"meaning":"hat"},
    "ゆかた": {"romaji":["yukata"],"meaning":"yukata"},
    "いえ": {"romaji":["ie"],"meaning":"house"},
    "まど": {"romaji":["mado"],"meaning":"window"},
    "かぎ": {"romaji":["kagi"],"meaning":"key"},
    "くつ": {"romaji":["kutsu"],"meaning":"shoes"},
    "てぶくろ": {"romaji":["tebukuro"],"meaning":"gloves"},
    "ちず": {"romaji":["chizu"],"meaning":"map"},
    "えんぴつ": {"romaji":["enpitsu"],"meaning":"pencil"},
    "ほん": {"romaji":["hon"],"meaning":"book"},
    "かみ": {"romaji":["kami"],"meaning":"paper"},
    "あたま": {"romaji":["atama"],"meaning":"head"},
    "おなか": {"romaji":["onaka"],"meaning":"stomach"},
    "からだ": {"romaji":["karada"],"meaning":"body"},
    "せなか": {"romaji":["senaka"],"meaning":"back"},
    "こころ": {"romaji":["kokoro"],"meaning":"heart"},
    "みみ": {"romaji":["mimi"],"meaning":"ear"},
    "くち": {"romaji":["kuchi"],"meaning":"mouth"},
    "め": {"romaji":["me"],"meaning":"eye"},
    "て": {"romaji":["te"],"meaning":"hand"},
    "あし": {"romaji":["ashi"],"meaning":"leg/foot"},
    "ゆび": {"romaji":["yubi"],"meaning":"finger"},
    "は": {"romaji":["ha"],"meaning":"tooth"},
    "かた": {"romaji":["kata"],"meaning":"shoulder"},
    "ひざ": {"romaji":["hiza"],"meaning":"knee"},
    "ひじ": {"romaji":["hiji"],"meaning":"elbow"},
    "くび": {"romaji":["kubi"],"meaning":"neck"},
    "まゆげ": {"romaji":["mayuge"],"meaning":"eyebrow"},
    "つめ": {"romaji":["tsume"],"meaning":"nail"},
    "ともだち": {"romaji":["tomodachi"],"meaning":"friend"},
    "こども": {"romaji":["kodomo"],"meaning":"child"},
    "おんな": {"romaji":["onna"],"meaning":"woman"},
    "おとこ": {"romaji":["otoko"],"meaning":"man"},
    "せんせい": {"romaji":["sensei"],"meaning":"teacher"},
    "いしゃ": {"romaji":["isha"],"meaning":"doctor"},
    "おかあさん": {"romaji":["okaasan"],"meaning":"mother"},
    "おとうさん": {"romaji":["otousan"],"meaning":"father"},
    "おねえさん": {"romaji":["oneesan"],"meaning":"older sister"},
    "おにいさん": {"romaji":["oniisan"],"meaning":"older brother"},
    "いもうと": {"romaji":["imouto"],"meaning":"younger sister"},
    "おとうと": {"romaji":["otouto"],"meaning":"younger brother"},
    "おじいさん": {"romaji":["ojiisan"],"meaning":"grandfather"},
    "おばあさん": {"romaji":["obaasan"],"meaning":"grandmother"},
    "こうえん": {"romaji":["kouen"],"meaning":"park"},
    "かいがん": {"romaji":["kaigan"],"meaning":"coast"},
    "くるま": {"romaji":["kuruma"],"meaning":"car"},
    "でんわ": {"romaji":["denwa"],"meaning":"telephone"},
    "がっこう": {"romaji":["gakkou"],"meaning":"school"},
    "えき": {"romaji":["eki"],"meaning":"station"},
    "びょういん": {"romaji":["byouin"],"meaning":"hospital"},
    "ぎんこう": {"romaji":["ginkou"],"meaning":"bank"},
    "としょかん": {"romaji":["toshokan"],"meaning":"library"},
    "ゆうびんきょく": {"romaji":["yuubinkyoku"],"meaning":"post office"},
    "どうぶつえん": {"romaji":["doubutsuen"],"meaning":"zoo"},
    "えいがかん": {"romaji":["eigakan"],"meaning":"movie theater"},
    "きっさてん": {"romaji":["kissaten"],"meaning":"cafe"},
    "でんしゃ": {"romaji":["densha"],"meaning":"train"},
    "じてんしゃ": {"romaji":["jitensha"],"meaning":"bicycle"},
    "ひこうき": {"romaji":["hikouki"],"meaning":"airplane"},
    "ふね": {"romaji":["fune"],"meaning":"ship/boat"},
    "ばす": {"romaji":["basu"],"meaning":"bus"},
    "ちかてつ": {"romaji":["chikatetsu"],"meaning":"subway"},
    "あかるい": {"romaji":["akarui"],"meaning":"bright"},
    "しずか": {"romaji":["shizuka"],"meaning":"quiet"},
    "たのしい": {"romaji":["tanoshii"],"meaning":"fun"},
    "うれしい": {"romaji":["ureshii"],"meaning":"happy"},
    "かなしい": {"romaji":["kanashii"],"meaning":"sad"},
    "はやい": {"romaji":["hayai"],"meaning":"fast"},
    "おそい": {"romaji":["osoi"],"meaning":"slow"},
    "あつい": {"romaji":["atsui"],"meaning":"hot/thick"},
    "さむい": {"romaji":["samui"],"meaning":"cold (weather)"},
    "つめたい": {"romaji":["tsumetai"],"meaning":"cold to touch"},
    "きれい": {"romaji":["kirei"],"meaning":"beautiful/clean"},
    "ちいさい": {"romaji":["chiisai"],"meaning":"small"},
    "おおきい": {"romaji":["ookii"],"meaning":"big"},
    "たかい": {"romaji":["takai"],"meaning":"expensive/tall"},
    "やすい": {"romaji":["yasui"],"meaning":"cheap"},
    "あたらしい": {"romaji":["atarashii"],"meaning":"new"},
    "ふるい": {"romaji":["furui"],"meaning":"old"},
    "むずかしい": {"romaji":["muzukashii"],"meaning":"difficult"},
    "やさしい": {"romaji":["yasashii"],"meaning":"easy/kind"},
    "とおい": {"romaji":["tooi"],"meaning":"far"},
    "ちかい": {"romaji":["chikai"],"meaning":"near"},
    "ひろい": {"romaji":["hiroi"],"meaning":"wide"},
    "せまい": {"romaji":["semai"],"meaning":"narrow"},
    "ねむい": {"romaji":["nemui"],"meaning":"sleepy"},
    "つよい": {"romaji":["tsuyoi"],"meaning":"strong"},
    "よわい": {"romaji":["yowai"],"meaning":"weak"},
    "あした": {"romaji":["ashita"],"meaning":"tomorrow"},
    "きのう": {"romaji":["kinou"],"meaning":"yesterday"},
    "きょう": {"romaji":["kyou"],"meaning":"today"},
    "あさ": {"romaji":["asa"],"meaning":"morning"},
    "よる": {"romaji":["yoru"],"meaning":"night"},
    "ひる": {"romaji":["hiru"],"meaning":"daytime"},
    "せかい": {"romaji":["sekai"],"meaning":"world"},
    "あか": {"romaji":["aka"],"meaning":"red"},
    "あお": {"romaji":["ao"],"meaning":"blue"},
    "しろ": {"romaji":["shiro"],"meaning":"white"},
    "くろ": {"romaji":["kuro"],"meaning":"black"},
    "きいろ": {"romaji":["kiiro"],"meaning":"yellow"},
    "みどり": {"romaji":["midori"],"meaning":"green"},
    "ちゃいろ": {"romaji":["chairo"],"meaning":"brown"},
    "むらさき": {"romaji":["murasaki"],"meaning":"purple"},
    "いち": {"romaji":["ichi"],"meaning":"one"},
    "に": {"romaji":["ni"],"meaning":"two"},
    "さん": {"romaji":["san"],"meaning":"three"},
    "よん": {"romaji":["yon"],"meaning":"four"},
    "ご": {"romaji":["go"],"meaning":"five"},
    "ろく": {"romaji":["roku"],"meaning":"six"},
    "なな": {"romaji":["nana"],"meaning":"seven"},
    "はち": {"romaji":["hachi"],"meaning":"eight"},
    "きゅう": {"romaji":["kyuu"],"meaning":"nine"},
    "じゅう": {"romaji":["juu"],"meaning":"ten"},
    "ひとつ": {"romaji":["hitotsu"],"meaning":"one (object)"},
    "ふたつ": {"romaji":["futatsu"],"meaning":"two (objects)"},
    "みっつ": {"romaji":["mittsu"],"meaning":"three (objects)"},
    "よっつ": {"romaji":["yottsu"],"meaning":"four (objects)"},
    "いつつ": {"romaji":["itsutsu"],"meaning":"five (objects)"},
    "むっつ": {"romaji":["muttsu"],"meaning":"six (objects)"},
    "ななつ": {"romaji":["nanatsu"],"meaning":"seven (objects)"},
    "やっつ": {"romaji":["yattsu"],"meaning":"eight (objects)"},
    "ここのつ": {"romaji":["kokonotsu"],"meaning":"nine (objects)"},
    "とお": {"romaji":["too"],"meaning":"ten (objects)"},
    "いくつ": {"romaji":["ikutsu"],"meaning":"how many?"},
    "たべる": {"romaji":["taberu"],"meaning":"to eat"},
    "のむ": {"romaji":["nomu"],"meaning":"to drink"},
    "ねる": {"romaji":["neru"],"meaning":"to sleep"},
    "おきる": {"romaji":["okiru"],"meaning":"to wake up"},
    "いく": {"romaji":["iku"],"meaning":"to go"},
    "くる": {"romaji":["kuru"],"meaning":"to come"},
    "かえる": {"romaji":["kaeru"],"meaning":"to return home"},
    "みる": {"romaji":["miru"],"meaning":"to see/watch"},
    "きく": {"romaji":["kiku"],"meaning":"to listen"},
    "かく": {"romaji":["kaku"],"meaning":"to write"},
    "よむ": {"romaji":["yomu"],"meaning":"to read"},
    "はなす": {"romaji":["hanasu"],"meaning":"to speak"},
    "かう": {"romaji":["kau"],"meaning":"to buy"},
    "あそぶ": {"romaji":["asobu"],"meaning":"to play"},
    "うま": {"romaji":["uma"],"meaning":"horse"},
    "うし": {"romaji":["ushi"],"meaning":"cow"},
    "ぶた": {"romaji":["buta"],"meaning":"pig"},
    "さる": {"romaji":["saru"],"meaning":"monkey"},
    "くま": {"romaji":["kuma"],"meaning":"bear"},
    "しか": {"romaji":["shika"],"meaning":"deer"},
    "へび": {"romaji":["hebi"],"meaning":"snake"},
    "かめ": {"romaji":["kame"],"meaning":"turtle"},
    "いか": {"romaji":["ika"],"meaning":"squid"},
    "たこ": {"romaji":["tako"],"meaning":"octopus"},
    "かに": {"romaji":["kani"],"meaning":"crab"},
    "えび": {"romaji":["ebi"],"meaning":"shrimp"},
    "あり": {"romaji":["ari"],"meaning":"ant"},
    "ちょう": {"romaji":["chou"],"meaning":"butterfly"},
    "とんぼ": {"romaji":["tonbo"],"meaning":"dragonfly"},
    "こうもり": {"romaji":["koumori"],"meaning":"bat"},
    "りす": {"romaji":["risu"],"meaning":"squirrel"},
    "はれ": {"romaji":["hare"],"meaning":"sunny weather"},
    "くもり": {"romaji":["kumori"],"meaning":"cloudy weather"},
    "あめふり": {"romaji":["amefuri"],"meaning":"rainy weather"},
    "あつさ": {"romaji":["atsusa"],"meaning":"heat"},
    "さむさ": {"romaji":["samusa"],"meaning":"cold"},
    "きせつ": {"romaji":["kisetsu"],"meaning":"season"},
    "いし": {"romaji":["ishi"],"meaning":"stone"},
    "すな": {"romaji":["suna"],"meaning":"sand"},
    "つち": {"romaji":["tsuchi"],"meaning":"earth, soil"},
    "き": {"romaji":["ki"],"meaning":"tree"},
    "くさ": {"romaji":["kusa"],"meaning":"grass"},
    "もり": {"romaji":["mori"],"meaning":"forest"},
    "はやし": {"romaji":["hayashi"],"meaning":"woods"},
    "たね": {"romaji":["tane"],"meaning":"seed"},
    "しま": {"romaji":["shima"],"meaning":"island"},
    "たに": {"romaji":["tani"],"meaning":"valley"},
    "いけ": {"romaji":["ike"],"meaning":"pond"},
    "なみ": {"romaji":["nami"],"meaning":"wave"},
    "ゆうがた": {"romaji":["yuugata"],"meaning":"evening"},
    "みず": {"romaji":["mizu"],"meaning":"water"},
    "こおり": {"romaji":["koori"],"meaning":"ice"},
    "ぎゅうにゅう": {"romaji":["gyuunyuu"],"meaning":"milk"},
    "こうちゃ": {"romaji":["koucha"],"meaning":"black tea"},
    "さけ": {"romaji":["sake"],"meaning":"sake, alcohol"},
    "にく": {"romaji":["niku"],"meaning":"meat"},
    "たまねぎ": {"romaji":["tamanegi"],"meaning":"onion"},
    "にんじん": {"romaji":["ninjin"],"meaning":"carrot"},
    "じゃがいも": {"romaji":["jagaimo"],"meaning":"potato"},
    "きゅうり": {"romaji":["kyuuri"],"meaning":"cucumber"},
    "なす": {"romaji":["nasu"],"meaning":"eggplant"},
    "だいこん": {"romaji":["daikon"],"meaning":"daikon radish"},
    "りんご": {"romaji":["ringo"],"meaning":"apple"},
    "みかん": {"romaji":["mikan"],"meaning":"mandarin orange"},
    "いちご": {"romaji":["ichigo"],"meaning":"strawberry"},
    "すいか": {"romaji":["suika"],"meaning":"watermelon"},
    "もも": {"romaji":["momo"],"meaning":"peach"},
    "なし": {"romaji":["nashi"],"meaning":"pear"},
    "あじ": {"romaji":["aji"],"meaning":"taste, flavour"},
    "あまい": {"romaji":["amai"],"meaning":"sweet"},
    "からい": {"romaji":["karai"],"meaning":"spicy"},
    "すっぱい": {"romaji":["suppai"],"meaning":"sour"},
    "にがい": {"romaji":["nigai"],"meaning":"bitter"},
    "いす": {"romaji":["isu"],"meaning":"chair"},
    "たな": {"romaji":["tana"],"meaning":"shelf"},
    "さら": {"romaji":["sara"],"meaning":"plate"},
    "ちゃわん": {"romaji":["chawan"],"meaning":"rice bowl"},
    "はし": {"romaji":["hashi"],"meaning":"chopsticks"},
    "なべ": {"romaji":["nabe"],"meaning":"pot"},
    "ふくろ": {"romaji":["fukuro"],"meaning":"bag"},
    "かびん": {"romaji":["kabin"],"meaning":"vase"},
    "ろうそく": {"romaji":["rousoku"],"meaning":"candle"},
    "かさ": {"romaji":["kasa"],"meaning":"umbrella"},
    "せんぷうき": {"romaji":["senpuuki"],"meaning":"electric fan"},
    "でんき": {"romaji":["denki"],"meaning":"electricity, light"},
    "かべ": {"romaji":["kabe"],"meaning":"wall"},
    "ゆか": {"romaji":["yuka"],"meaning":"floor"},
    "てんじょう": {"romaji":["tenjou"],"meaning":"ceiling"},
    "にわ": {"romaji":["niwa"],"meaning":"garden"},
    "げんかん": {"romaji":["genkan"],"meaning":"entrance"},
    "おふろ": {"romaji":["ofuro"],"meaning":"bath"},
    "だいどころ": {"romaji":["daidokoro"],"meaning":"kitchen"},
    "いれもの": {"romaji":["iremono"],"meaning":"container"},
    "さいばし": {"romaji":["saibashi"],"meaning":"cooking chopsticks"},
    "かお": {"romaji":["kao"],"meaning":"face"},
    "ひたい": {"romaji":["hitai"],"meaning":"forehead"},
    "ほほ": {"romaji":["hoho"],"meaning":"cheek"},
    "あご": {"romaji":["ago"],"meaning":"chin, jaw"},
    "うで": {"romaji":["ude"],"meaning":"arm"},
    "ゆびさき": {"romaji":["yubisaki"],"meaning":"fingertip"},
    "むね": {"romaji":["mune"],"meaning":"chest"},
    "こし": {"romaji":["koshi"],"meaning":"waist, lower back"},
    "こえ": {"romaji":["koe"],"meaning":"voice"},
    "かみのけ": {"romaji":["kaminoke"],"meaning":"hair"},
    "した": {"romaji":["shita"],"meaning":"tongue"},
    "のど": {"romaji":["nodo"],"meaning":"throat"},
    "いき": {"romaji":["iki"],"meaning":"breath"},
    "かぞく": {"romaji":["kazoku"],"meaning":"family"},
    "かない": {"romaji":["kanai"],"meaning":"one's wife"},
    "しゅじん": {"romaji":["shujin"],"meaning":"one's husband"},
    "あかちゃん": {"romaji":["akachan"],"meaning":"baby"},
    "おとな": {"romaji":["otona"],"meaning":"adult"},
    "わかもの": {"romaji":["wakamono"],"meaning":"young person"},
    "となり": {"romaji":["tonari"],"meaning":"neighbour"},
    "しんせき": {"romaji":["shinseki"],"meaning":"relatives"},
    "いとこ": {"romaji":["itoko"],"meaning":"cousin"},
    "おじさん": {"romaji":["ojisan"],"meaning":"uncle, middle-aged man"},
    "おばさん": {"romaji":["obasan"],"meaning":"aunt, middle-aged woman"},
    "しゃちょう": {"romaji":["shachou"],"meaning":"company president"},
    "がくせい": {"romaji":["gakusei"],"meaning":"student"},
    "せいと": {"romaji":["seito"],"meaning":"pupil"},
    "みち": {"romaji":["michi"],"meaning":"road"},
    "こうさてん": {"romaji":["kousaten"],"meaning":"intersection"},
    "しんごう": {"romaji":["shingou"],"meaning":"traffic light"},
    "ちゅうしゃじょう": {"romaji":["chuushajou"],"meaning":"parking lot"},
    "こうじょう": {"romaji":["koujou"],"meaning":"factory"},
    "かいしゃ": {"romaji":["kaisha"],"meaning":"company"},
    "みせ": {"romaji":["mise"],"meaning":"shop"},
    "いちば": {"romaji":["ichiba"],"meaning":"market"},
    "こうばん": {"romaji":["kouban"],"meaning":"police box"},
    "じんじゃ": {"romaji":["jinja"],"meaning":"shrine"},
    "おてら": {"romaji":["otera"],"meaning":"temple"},
    "おしろ": {"romaji":["oshiro"],"meaning":"castle"},
    "たいしかん": {"romaji":["taishikan"],"meaning":"embassy"},
    "せき": {"romaji":["seki"],"meaning":"seat"},
    "わかい": {"romaji":["wakai"],"meaning":"young"},
    "としより": {"romaji":["toshiyori"],"meaning":"elderly"},
    "ながい": {"romaji":["nagai"],"meaning":"long"},
    "みじかい": {"romaji":["mijikai"],"meaning":"short (length)"},
    "ひくい": {"romaji":["hikui"],"meaning":"low"},
    "おもい": {"romaji":["omoi"],"meaning":"heavy"},
    "かるい": {"romaji":["karui"],"meaning":"light (weight)"},
    "かたい": {"romaji":["katai"],"meaning":"hard"},
    "やわらかい": {"romaji":["yawarakai"],"meaning":"soft"},
    "あたたかい": {"romaji":["atatakai"],"meaning":"warm"},
    "すずしい": {"romaji":["suzushii"],"meaning":"cool"},
    "くらい": {"romaji":["kurai"],"meaning":"dark"},
    "うるさい": {"romaji":["urusai"],"meaning":"noisy"},
    "いそがしい": {"romaji":["isogashii"],"meaning":"busy"},
    "ひま": {"romaji":["hima"],"meaning":"free time"},
    "げんき": {"romaji":["genki"],"meaning":"energetic, well"},
    "あぶない": {"romaji":["abunai"],"meaning":"dangerous"},
    "あんぜん": {"romaji":["anzen"],"meaning":"safe"},
    "べんり": {"romaji":["benri"],"meaning":"convenient"},
    "ふべん": {"romaji":["fuben"],"meaning":"inconvenient"},
    "ゆうめい": {"romaji":["yuumei"],"meaning":"famous"},
    "たいせつ": {"romaji":["taisetsu"],"meaning":"important, precious"},
    "いろいろ": {"romaji":["iroiro"],"meaning":"various"},
    "おなじ": {"romaji":["onaji"],"meaning":"same"},
    "ちがう": {"romaji":["chigau"],"meaning":"different, wrong"},
    "いま": {"romaji":["ima"],"meaning":"now"},
    "あとで": {"romaji":["atode"],"meaning":"later"},
    "さっき": {"romaji":["sakki"],"meaning":"a moment ago"},
    "まいにち": {"romaji":["mainichi"],"meaning":"every day"},
    "まいあさ": {"romaji":["maiasa"],"meaning":"every morning"},
    "まいばん": {"romaji":["maiban"],"meaning":"every evening"},
    "ひごろ": {"romaji":["higoro"],"meaning":"usually"},
    "しゅうまつ": {"romaji":["shuumatsu"],"meaning":"weekend"},
    "こんしゅう": {"romaji":["konshuu"],"meaning":"this week"},
    "らいしゅう": {"romaji":["raishuu"],"meaning":"next week"},
    "せんしゅう": {"romaji":["senshuu"],"meaning":"last week"},
    "こんげつ": {"romaji":["kongetsu"],"meaning":"this month"},
    "らいねん": {"romaji":["rainen"],"meaning":"next year"},
    "きょねん": {"romaji":["kyonen"],"meaning":"last year"},
    "ことし": {"romaji":["kotoshi"],"meaning":"this year"},
    "じかん": {"romaji":["jikan"],"meaning":"time, hour"},
    "ふん": {"romaji":["fun"],"meaning":"minute"},
    "びょう": {"romaji":["byou"],"meaning":"second"},
    "いつも": {"romaji":["itsumo"],"meaning":"always"},
    "ときどき": {"romaji":["tokidoki"],"meaning":"sometimes"},
    "ももいろ": {"romaji":["momoiro"],"meaning":"pink"},
    "そらいろ": {"romaji":["sorairo"],"meaning":"sky blue"},
    "はいいろ": {"romaji":["haiiro"],"meaning":"grey"},
    "こんいろ": {"romaji":["kon'iro"],"meaning":"navy blue"},
    "きんいろ": {"romaji":["kin'iro"],"meaning":"gold"},
    "ぎんいろ": {"romaji":["gin'iro"],"meaning":"silver"},
    "だいだいいろ": {"romaji":["daidaiiro"],"meaning":"orange"},
    "ぜろ": {"romaji":["zero"],"meaning":"zero"},
    "ひゃく": {"romaji":["hyaku"],"meaning":"hundred"},
    "せん": {"romaji":["sen"],"meaning":"thousand"},
    "まん": {"romaji":["man"],"meaning":"ten thousand"},
    "にじゅう": {"romaji":["nijuu"],"meaning":"twenty"},
    "さんじゅう": {"romaji":["sanjuu"],"meaning":"thirty"},
    "ごじゅう": {"romaji":["gojuu"],"meaning":"fifty"},
    "はんぶん": {"romaji":["hanbun"],"meaning":"half"},
    "いちまい": {"romaji":["ichimai"],"meaning":"one (flat object)"},
    "にまい": {"romaji":["nimai"],"meaning":"two (flat objects)"},
    "いちにん": {"romaji":["ichinin"],"meaning":"one person"},
    "ふたり": {"romaji":["futari"],"meaning":"two people"},
    "さんにん": {"romaji":["sannin"],"meaning":"three people"},
    "いっぴき": {"romaji":["ippiki"],"meaning":"one (small animal)"},
    "にひき": {"romaji":["nihiki"],"meaning":"two (small animals)"},
    "いっさつ": {"romaji":["issatsu"],"meaning":"one (book)"},
    "にさつ": {"romaji":["nisatsu"],"meaning":"two (books)"},
    "いっぽん": {"romaji":["ippon"],"meaning":"one (long object)"},
    "にほん": {"romaji":["nihon"],"meaning":"two (long objects)"},
    "いっかい": {"romaji":["ikkai"],"meaning":"once, first floor"},
    "にかい": {"romaji":["nikai"],"meaning":"twice, second floor"},
    "はしる": {"romaji":["hashiru"],"meaning":"to run"},
    "あるく": {"romaji":["aruku"],"meaning":"to walk"},
    "およぐ": {"romaji":["oyogu"],"meaning":"to swim"},
    "とぶ": {"romaji":["tobu"],"meaning":"to fly, to jump"},
    "すわる": {"romaji":["suwaru"],"meaning":"to sit"},
    "たつ": {"romaji":["tatsu"],"meaning":"to stand"},
    "わらう": {"romaji":["warau"],"meaning":"to laugh"},
    "なく": {"romaji":["naku"],"meaning":"to cry"},
    "おこる": {"romaji":["okoru"],"meaning":"to get angry"},
    "あける": {"romaji":["akeru"],"meaning":"to open"},
    "しめる": {"romaji":["shimeru"],"meaning":"to close"},
    "いれる": {"romaji":["ireru"],"meaning":"to put in"},
    "だす": {"romaji":["dasu"],"meaning":"to take out"},
    "つける": {"romaji":["tsukeru"],"meaning":"to turn on"},
    "けす": {"romaji":["kesu"],"meaning":"to turn off, erase"},
    "まつ": {"romaji":["matsu"],"meaning":"to wait"},
    "つかう": {"romaji":["tsukau"],"meaning":"to use"},
    "つくる": {"romaji":["tsukuru"],"meaning":"to make"},
    "あらう": {"romaji":["arau"],"meaning":"to wash"},
    "そうじする": {"romaji":["soujisuru"],"meaning":"to clean"},
    "はたらく": {"romaji":["hataraku"],"meaning":"to work"},
    "やすむ": {"romaji":["yasumu"],"meaning":"to rest"},
    "わかる": {"romaji":["wakaru"],"meaning":"to understand"},
    "しる": {"romaji":["shiru"],"meaning":"to know"},
    "わすれる": {"romaji":["wasureru"],"meaning":"to forget"},
    "おぼえる": {"romaji":["oboeru"],"meaning":"to remember"},
    "おしえる": {"romaji":["oshieru"],"meaning":"to teach"},
    "ならう": {"romaji":["narau"],"meaning":"to learn"},
    "えらぶ": {"romaji":["erabu"],"meaning":"to choose"},
    "さがす": {"romaji":["sagasu"],"meaning":"to search for"},
    "しあわせ": {"romaji":["shiawase"],"meaning":"happiness"},
    "さびしい": {"romaji":["sabishii"],"meaning":"lonely"},
    "こわい": {"romaji":["kowai"],"meaning":"scary, afraid"},
    "びっくり": {"romaji":["bikkuri"],"meaning":"surprised"},
    "すき": {"romaji":["suki"],"meaning":"like, favourite"},
    "だいすき": {"romaji":["daisuki"],"meaning":"love, really like"},
    "きらい": {"romaji":["kirai"],"meaning":"dislike"},
    "だいきらい": {"romaji":["daikirai"],"meaning":"hate"},
    "はずかしい": {"romaji":["hazukashii"],"meaning":"embarrassed"},
    "しんぱい": {"romaji":["shinpai"],"meaning":"worry"},
    "あんしん": {"romaji":["anshin"],"meaning":"peace of mind"},
    "たのしみ": {"romaji":["tanoshimi"],"meaning":"looking forward to"},
    "ゆめ": {"romaji":["yume"],"meaning":"dream"},
    "きぼう": {"romaji":["kibou"],"meaning":"hope"},
    "きもち": {"romaji":["kimochi"],"meaning":"feeling"},
    "あいする": {"romaji":["aisuru"],"meaning":"to love"},
    "いや": {"romaji":["iya"],"meaning":"unpleasant, no"},
    "だめ": {"romaji":["dame"],"meaning":"no good, useless"},
    "こんにちは": {"romaji":["konnichiwa"],"meaning":"hello, good afternoon"},
    "おはよう": {"romaji":["ohayou"],"meaning":"good morning"},
    "こんばんは": {"romaji":["konbanwa"],"meaning":"good evening"},
    "おやすみ": {"romaji":["oyasumi"],"meaning":"good night"},
    "さようなら": {"romaji":["sayounara"],"meaning":"goodbye"},
    "ありがとう": {"romaji":["arigatou"],"meaning":"thank you"},
    "どういたしまして": {"romaji":["douitashimashite"],"meaning":"you're welcome"},
    "すみません": {"romaji":["sumimasen"],"meaning":"excuse me, sorry"},
    "ごめんなさい": {"romaji":["gomennasai"],"meaning":"I'm sorry"},
    "はじめまして": {"romaji":["hajimemashite"],"meaning":"nice to meet you"},
    "おねがいします": {"romaji":["onegaishimasu"],"meaning":"please"},
    "いただきます": {"romaji":["itadakimasu"],"meaning":"(said before eating)"},
    "ごちそうさま": {"romaji":["gochisousama"],"meaning":"(said after eating)"},
    "いってきます": {"romaji":["ittekimasu"],"meaning":"I'm off"},
    "いってらっしゃい": {"romaji":["itterasshai"],"meaning":"see you (to someone leaving)"},
    "ただいま": {"romaji":["tadaima"],"meaning":"I'm home"},
    "おかえり": {"romaji":["okaeri"],"meaning":"welcome home"},
    "がんばって": {"romaji":["ganbatte"],"meaning":"do your best"},
    "だいじょうぶ": {"romaji":["daijoubu"],"meaning":"OK, all right"},
    "もちろん": {"romaji":["mochiron"],"meaning":"of course"},
    "わんわん": {"romaji":["wanwan"],"meaning":"woof (dog)"},
    "にゃんにゃん": {"romaji":["nyannyan"],"meaning":"meow (cat)"},
    "こけこっこう": {"romaji":["kokekokkou"],"meaning":"cock-a-doodle-doo"},
    "かあかあ": {"romaji":["kaakaa"],"meaning":"caw (crow)"},
    "ぶうぶう": {"romaji":["buubuu"],"meaning":"oink (pig)"},
    "もうもう": {"romaji":["moumou"],"meaning":"moo (cow)"},
    "ぴかぴか": {"romaji":["pikapika"],"meaning":"sparkling"},
    "きらきら": {"romaji":["kirakira"],"meaning":"glittering, twinkling"},
    "ふわふわ": {"romaji":["fuwafuwa"],"meaning":"fluffy"},
    "さらさら": {"romaji":["sarasara"],"meaning":"smooth, silky"},
    "べたべた": {"romaji":["betabeta"],"meaning":"sticky"},
    "ざあざあ": {"romaji":["zaazaa"],"meaning":"heavy rain"},
    "しとしと": {"romaji":["shitoshito"],"meaning":"drizzling"},
    "ごろごろ": {"romaji":["gorogoro"],"meaning":"thunder rumbling"},
    "にこにこ": {"romaji":["nikoniko"],"meaning":"smiling"},
    "わくわく": {"romaji":["wakuwaku"],"meaning":"excited"},
    "どきどき": {"romaji":["dokidoki"],"meaning":"heart pounding"},
    "ぺこぺこ": {"romaji":["pekopeko"],"meaning":"hungry (stomach)"},
    "ぐっすり": {"romaji":["gussuri"],"meaning":"sound asleep"},
    "ゆっくり": {"romaji":["yukkuri"],"meaning":"slowly, leisurely"},
    "べんきょう": {"romaji":["benkyou"],"meaning":"study"},
    "しゅくだい": {"romaji":["shukudai"],"meaning":"homework"},
    "じゅぎょう": {"romaji":["jugyou"],"meaning":"class, lesson"},
    "きょうしつ": {"romaji":["kyoushitsu"],"meaning":"classroom"},
    "こくばん": {"romaji":["kokuban"],"meaning":"blackboard"},
    "けしごむ": {"romaji":["keshigomu"],"meaning":"eraser"},
    "ものさし": {"romaji":["monosashi"],"meaning":"ruler"},
    "ちょうさ": {"romaji":["chousa"],"meaning":"investigation"},
    "しつもん": {"romaji":["shitsumon"],"meaning":"question"},
    "こたえ": {"romaji":["kotae"],"meaning":"answer"},
    "せいかい": {"romaji":["seikai"],"meaning":"correct answer"},
    "まちがい": {"romaji":["machigai"],"meaning":"mistake"},
    "えんそく": {"romaji":["ensoku"],"meaning":"school excursion"},
    "なつやすみ": {"romaji":["natsuyasumi"],"meaning":"summer vacation"},
    "ふゆやすみ": {"romaji":["fuyuyasumi"],"meaning":"winter vacation"},
    "そつぎょう": {"romaji":["sotsugyou"],"meaning":"graduation"},
    "にゅうがく": {"romaji":["nyuugaku"],"meaning":"school entrance"},
    "せいふく": {"romaji":["seifuku"],"meaning":"school uniform"},
    "なまえ": {"romaji":["namae"],"meaning":"name"},
    "ふく": {"romaji":["fuku"],"meaning":"clothes"},
    "ようふく": {"romaji":["youfuku"],"meaning":"Western clothes"},
    "きもの": {"romaji":["kimono"],"meaning":"kimono"},
    "じんべい": {"romaji":["jinbei"],"meaning":"summer kimono"},
    "したぎ": {"romaji":["shitagi"],"meaning":"underwear"},
    "うわぎ": {"romaji":["uwagi"],"meaning":"jacket, coat"},
    "ゆびわ": {"romaji":["yubiwa"],"meaning":"ring"},
    "うでどけい": {"romaji":["udedokei"],"meaning":"wristwatch"},
    "かみかざり": {"romaji":["kamikazari"],"meaning":"hair ornament"},
    "えりまき": {"romaji":["erimaki"],"meaning":"scarf"},
    "うえ": {"romaji":["ue"],"meaning":"up, above"},
    "まえ": {"romaji":["mae"],"meaning":"front, before"},
    "うしろ": {"romaji":["ushiro"],"meaning":"behind"},
    "みぎ": {"romaji":["migi"],"meaning":"right"},
    "ひだり": {"romaji":["hidari"],"meaning":"left"},
    "あいだ": {"romaji":["aida"],"meaning":"between"},
    "そば": {"romaji":["soba"],"meaning":"beside, near"},
    "なか": {"romaji":["naka"],"meaning":"inside, middle"},
    "そと": {"romaji":["soto"],"meaning":"outside"},
    "きた": {"romaji":["kita"],"meaning":"north"},
    "みなみ": {"romaji":["minami"],"meaning":"south"},
    "ひがし": {"romaji":["higashi"],"meaning":"east"},
    "にし": {"romaji":["nishi"],"meaning":"west"},
    "ここ": {"romaji":["koko"],"meaning":"here"},
    "そこ": {"romaji":["soko"],"meaning":"there"},
    "あそこ": {"romaji":["asoko"],"meaning":"over there"},
    "どこ": {"romaji":["doko"],"meaning":"where"},
    "むこう": {"romaji":["mukou"],"meaning":"the other side"}
  
  }
};

const HIRAGANA_VOCAB_DATA_SUBCATEGORIES = {
    "ANIMALS": {
        "ねこ": {"romaji":["neko"],"meaning":"cat"},
        "いぬ": {"romaji":["inu"],"meaning":"dog"},
        "とり": {"romaji":["tori"],"meaning":"bird"},
        "うさぎ": {"romaji":["usagi"],"meaning":"rabbit"},
        "からす": {"romaji":["karasu"],"meaning":"crow"},
        "きつね": {"romaji":["kitsune"],"meaning":"fox"},
        "すずめ": {"romaji":["suzume"],"meaning":"sparrow"},
        "たぬき": {"romaji":["tanuki"],"meaning":"raccoon dog"},
        "ねずみ": {"romaji":["nezumi"],"meaning":"mouse"},
        "ひつじ": {"romaji":["hitsuji"],"meaning":"sheep"},
        "めだか": {"romaji":["medaka"],"meaning":"killifish"},
        "くじら": {"romaji":["kujira"],"meaning":"whale"},
    "うま": {"romaji":["uma"],"meaning":"horse"},
    "うし": {"romaji":["ushi"],"meaning":"cow"},
    "ぶた": {"romaji":["buta"],"meaning":"pig"},
    "さる": {"romaji":["saru"],"meaning":"monkey"},
    "くま": {"romaji":["kuma"],"meaning":"bear"},
    "しか": {"romaji":["shika"],"meaning":"deer"},
    "へび": {"romaji":["hebi"],"meaning":"snake"},
    "かめ": {"romaji":["kame"],"meaning":"turtle"},
    "いか": {"romaji":["ika"],"meaning":"squid"},
    "たこ": {"romaji":["tako"],"meaning":"octopus"},
    "かに": {"romaji":["kani"],"meaning":"crab"},
    "えび": {"romaji":["ebi"],"meaning":"shrimp"},
    "あり": {"romaji":["ari"],"meaning":"ant"},
    "ちょう": {"romaji":["chou"],"meaning":"butterfly"},
    "とんぼ": {"romaji":["tonbo"],"meaning":"dragonfly"},
    "こうもり": {"romaji":["koumori"],"meaning":"bat"},
    "りす": {"romaji":["risu"],"meaning":"squirrel"}
  
    },
    "NATURE & WEATHER": {
        "さくら": {"romaji":["sakura"],"meaning":"cherry blossom"},
        "ひまわり": {"romaji":["himawari"],"meaning":"sunflower"},
        "あさがお": {"romaji":["asagao"],"meaning":"morning glory"},
        "もみじ": {"romaji":["momiji"],"meaning":"maple"},
        "たけのこ": {"romaji":["takenoko"],"meaning":"bamboo shoot"},
        "かみなり": {"romaji":["kaminari"],"meaning":"thunder"},
        "みずうみ": {"romaji":["mizuumi"],"meaning":"lake"},
        "あらし": {"romaji":["arashi"],"meaning":"storm"},
        "あめ": {"romaji":["ame"],"meaning":"rain"},
        "ゆき": {"romaji":["yuki"],"meaning":"snow"},
        "そら": {"romaji":["sora"],"meaning":"sky"},
        "ほし": {"romaji":["hoshi"],"meaning":"star"},
        "つき": {"romaji":["tsuki"],"meaning":"moon"},
        "やま": {"romaji":["yama"],"meaning":"mountain"},
        "かわ": {"romaji":["kawa"],"meaning":"river"},
        "うみ": {"romaji":["umi"],"meaning":"sea"},
        "はな": {"romaji":["hana"],"meaning":"flower"},
        "はる": {"romaji":["haru"],"meaning":"spring"},
        "なつ": {"romaji":["natsu"],"meaning":"summer"},
        "あき": {"romaji":["aki"],"meaning":"autumn"},
        "ふゆ": {"romaji":["fuyu"],"meaning":"winter"},
        "くも": {"romaji":["kumo"],"meaning":"cloud"},
        "かぜ": {"romaji":["kaze"],"meaning":"wind"},
        "たいよう": {"romaji":["taiyou"],"meaning":"sun"},
        "にじ": {"romaji":["niji"],"meaning":"rainbow"},
        "きり": {"romaji":["kiri"],"meaning":"fog"},
    "はれ": {"romaji":["hare"],"meaning":"sunny weather"},
    "くもり": {"romaji":["kumori"],"meaning":"cloudy weather"},
    "あめふり": {"romaji":["amefuri"],"meaning":"rainy weather"},
    "あつさ": {"romaji":["atsusa"],"meaning":"heat"},
    "さむさ": {"romaji":["samusa"],"meaning":"cold"},
    "きせつ": {"romaji":["kisetsu"],"meaning":"season"},
    "いし": {"romaji":["ishi"],"meaning":"stone"},
    "すな": {"romaji":["suna"],"meaning":"sand"},
    "つち": {"romaji":["tsuchi"],"meaning":"earth, soil"},
    "き": {"romaji":["ki"],"meaning":"tree"},
    "くさ": {"romaji":["kusa"],"meaning":"grass"},
    "もり": {"romaji":["mori"],"meaning":"forest"},
    "はやし": {"romaji":["hayashi"],"meaning":"woods"},
    "たね": {"romaji":["tane"],"meaning":"seed"},
    "しま": {"romaji":["shima"],"meaning":"island"},
    "たに": {"romaji":["tani"],"meaning":"valley"},
    "いけ": {"romaji":["ike"],"meaning":"pond"},
    "なみ": {"romaji":["nami"],"meaning":"wave"},
    "ゆうがた": {"romaji":["yuugata"],"meaning":"evening"}
  
    },
    "FOOD & DRINK": {
        "おにぎり": {"romaji":["onigiri"],"meaning":"rice ball"},
        "たまご": {"romaji":["tamago"],"meaning":"egg"},
        "さかな": {"romaji":["sakana"],"meaning":"fish"},
        "くだもの": {"romaji":["kudamono"],"meaning":"fruit"},
        "やさい": {"romaji":["yasai"],"meaning":"vegetable"},
        "ごはん": {"romaji":["gohan"],"meaning":"meal/rice"},
        "おちゃ": {"romaji":["ocha"],"meaning":"green tea"},
        "おかし": {"romaji":["okashi"],"meaning":"sweets"},
        "みそしる": {"romaji":["misoshiru"],"meaning":"miso soup"},
        "てんぷら": {"romaji":["tenpura"],"meaning":"tempura"},
        "さとう": {"romaji":["satou"],"meaning":"sugar"},
        "しお": {"romaji":["shio"],"meaning":"salt"},
        "わさび": {"romaji":["wasabi"],"meaning":"wasabi"},
        "あずき": {"romaji":["azuki"],"meaning":"red bean"},
        "おべんとう": {"romaji":["obentou"],"meaning":"lunch box"},
        "のみもの": {"romaji":["nomimono"],"meaning":"drink"},
        "たべもの": {"romaji":["tabemono"],"meaning":"food"},
        "おかず": {"romaji":["okazu"],"meaning":"side dish"},
        "おいしい": {"romaji":["oishii"],"meaning":"delicious"},
        "まずい": {"romaji":["mazui"],"meaning":"tastes bad"},
    "みず": {"romaji":["mizu"],"meaning":"water"},
    "こおり": {"romaji":["koori"],"meaning":"ice"},
    "ぎゅうにゅう": {"romaji":["gyuunyuu"],"meaning":"milk"},
    "こうちゃ": {"romaji":["koucha"],"meaning":"black tea"},
    "さけ": {"romaji":["sake"],"meaning":"sake, alcohol"},
    "にく": {"romaji":["niku"],"meaning":"meat"},
    "たまねぎ": {"romaji":["tamanegi"],"meaning":"onion"},
    "にんじん": {"romaji":["ninjin"],"meaning":"carrot"},
    "じゃがいも": {"romaji":["jagaimo"],"meaning":"potato"},
    "きゅうり": {"romaji":["kyuuri"],"meaning":"cucumber"},
    "なす": {"romaji":["nasu"],"meaning":"eggplant"},
    "だいこん": {"romaji":["daikon"],"meaning":"daikon radish"},
    "りんご": {"romaji":["ringo"],"meaning":"apple"},
    "みかん": {"romaji":["mikan"],"meaning":"mandarin orange"},
    "いちご": {"romaji":["ichigo"],"meaning":"strawberry"},
    "すいか": {"romaji":["suika"],"meaning":"watermelon"},
    "もも": {"romaji":["momo"],"meaning":"peach"},
    "なし": {"romaji":["nashi"],"meaning":"pear"},
    "あじ": {"romaji":["aji"],"meaning":"taste, flavour"},
    "あまい": {"romaji":["amai"],"meaning":"sweet"},
    "からい": {"romaji":["karai"],"meaning":"spicy"},
    "すっぱい": {"romaji":["suppai"],"meaning":"sour"},
    "にがい": {"romaji":["nigai"],"meaning":"bitter"}
  
    },
    "HOUSEHOLD & OBJECTS": {
        "つくえ": {"romaji":["tsukue"],"meaning":"desk"},
        "ほうき": {"romaji":["houki"],"meaning":"broom"},
        "かがみ": {"romaji":["kagami"],"meaning":"mirror"},
        "とけい": {"romaji":["tokei"],"meaning":"clock/watch"},
        "めがね": {"romaji":["megane"],"meaning":"glasses"},
        "かばん": {"romaji":["kaban"],"meaning":"bag"},
        "さいふ": {"romaji":["saifu"],"meaning":"wallet"},
        "はさみ": {"romaji":["hasami"],"meaning":"scissors"},
        "ふでばこ": {"romaji":["fudebako"],"meaning":"pencil case"},
        "じしょ": {"romaji":["jisho"],"meaning":"dictionary"},
        "しんぶん": {"romaji":["shinbun"],"meaning":"newspaper"},
        "てがみ": {"romaji":["tegami"],"meaning":"letter"},
        "ふとん": {"romaji":["futon"],"meaning":"futon"},
        "まくら": {"romaji":["makura"],"meaning":"pillow"},
        "せっけん": {"romaji":["sekken"],"meaning":"soap"},
        "くつした": {"romaji":["kutsushita"],"meaning":"socks"},
        "ぼうし": {"romaji":["boushi"],"meaning":"hat"},
        "ゆかた": {"romaji":["yukata"],"meaning":"yukata"},
        "いえ": {"romaji":["ie"],"meaning":"house"},
        "まど": {"romaji":["mado"],"meaning":"window"},
        "かぎ": {"romaji":["kagi"],"meaning":"key"},
        "くつ": {"romaji":["kutsu"],"meaning":"shoes"},
        "てぶくろ": {"romaji":["tebukuro"],"meaning":"gloves"},
        "ちず": {"romaji":["chizu"],"meaning":"map"},
        "えんぴつ": {"romaji":["enpitsu"],"meaning":"pencil"},
        "ほん": {"romaji":["hon"],"meaning":"book"},
        "かみ": {"romaji":["kami"],"meaning":"paper"},
    "いす": {"romaji":["isu"],"meaning":"chair"},
    "たな": {"romaji":["tana"],"meaning":"shelf"},
    "さら": {"romaji":["sara"],"meaning":"plate"},
    "ちゃわん": {"romaji":["chawan"],"meaning":"rice bowl"},
    "はし": {"romaji":["hashi"],"meaning":"chopsticks"},
    "なべ": {"romaji":["nabe"],"meaning":"pot"},
    "ふくろ": {"romaji":["fukuro"],"meaning":"bag"},
    "かびん": {"romaji":["kabin"],"meaning":"vase"},
    "ろうそく": {"romaji":["rousoku"],"meaning":"candle"},
    "かさ": {"romaji":["kasa"],"meaning":"umbrella"},
    "せんぷうき": {"romaji":["senpuuki"],"meaning":"electric fan"},
    "でんき": {"romaji":["denki"],"meaning":"electricity, light"},
    "かべ": {"romaji":["kabe"],"meaning":"wall"},
    "ゆか": {"romaji":["yuka"],"meaning":"floor"},
    "てんじょう": {"romaji":["tenjou"],"meaning":"ceiling"},
    "にわ": {"romaji":["niwa"],"meaning":"garden"},
    "げんかん": {"romaji":["genkan"],"meaning":"entrance"},
    "おふろ": {"romaji":["ofuro"],"meaning":"bath"},
    "だいどころ": {"romaji":["daidokoro"],"meaning":"kitchen"},
    "いれもの": {"romaji":["iremono"],"meaning":"container"},
    "さいばし": {"romaji":["saibashi"],"meaning":"cooking chopsticks"}
  
    },
    "BODY PARTS": {
        "あたま": {"romaji":["atama"],"meaning":"head"},
        "おなか": {"romaji":["onaka"],"meaning":"stomach"},
        "からだ": {"romaji":["karada"],"meaning":"body"},
        "せなか": {"romaji":["senaka"],"meaning":"back"},
        "こころ": {"romaji":["kokoro"],"meaning":"heart"},
        "みみ": {"romaji":["mimi"],"meaning":"ear"},
        "くち": {"romaji":["kuchi"],"meaning":"mouth"},
        "め": {"romaji":["me"],"meaning":"eye"},
        "て": {"romaji":["te"],"meaning":"hand"},
        "あし": {"romaji":["ashi"],"meaning":"leg/foot"},
        "ゆび": {"romaji":["yubi"],"meaning":"finger"},
        "は": {"romaji":["ha"],"meaning":"tooth"},
        "かた": {"romaji":["kata"],"meaning":"shoulder"},
        "ひざ": {"romaji":["hiza"],"meaning":"knee"},
        "ひじ": {"romaji":["hiji"],"meaning":"elbow"},
        "くび": {"romaji":["kubi"],"meaning":"neck"},
        "まゆげ": {"romaji":["mayuge"],"meaning":"eyebrow"},
        "つめ": {"romaji":["tsume"],"meaning":"nail"},
    "かお": {"romaji":["kao"],"meaning":"face"},
    "ひたい": {"romaji":["hitai"],"meaning":"forehead"},
    "ほほ": {"romaji":["hoho"],"meaning":"cheek"},
    "あご": {"romaji":["ago"],"meaning":"chin, jaw"},
    "うで": {"romaji":["ude"],"meaning":"arm"},
    "ゆびさき": {"romaji":["yubisaki"],"meaning":"fingertip"},
    "むね": {"romaji":["mune"],"meaning":"chest"},
    "こし": {"romaji":["koshi"],"meaning":"waist, lower back"},
    "こえ": {"romaji":["koe"],"meaning":"voice"},
    "かみのけ": {"romaji":["kaminoke"],"meaning":"hair"},
    "した": {"romaji":["shita"],"meaning":"tongue"},
    "のど": {"romaji":["nodo"],"meaning":"throat"},
    "いき": {"romaji":["iki"],"meaning":"breath"}
  
    },
    "PEOPLE & FAMILY": {
        "ともだち": {"romaji":["tomodachi"],"meaning":"friend"},
        "こども": {"romaji":["kodomo"],"meaning":"child"},
        "おんな": {"romaji":["onna"],"meaning":"woman"},
        "おとこ": {"romaji":["otoko"],"meaning":"man"},
        "せんせい": {"romaji":["sensei"],"meaning":"teacher"},
        "いしゃ": {"romaji":["isha"],"meaning":"doctor"},
        "おかあさん": {"romaji":["okaasan"],"meaning":"mother"},
        "おとうさん": {"romaji":["otousan"],"meaning":"father"},
        "おねえさん": {"romaji":["oneesan"],"meaning":"older sister"},
        "おにいさん": {"romaji":["oniisan"],"meaning":"older brother"},
        "いもうと": {"romaji":["imouto"],"meaning":"younger sister"},
        "おとうと": {"romaji":["otouto"],"meaning":"younger brother"},
        "おじいさん": {"romaji":["ojiisan"],"meaning":"grandfather"},
        "おばあさん": {"romaji":["obaasan"],"meaning":"grandmother"},
    "かぞく": {"romaji":["kazoku"],"meaning":"family"},
    "かない": {"romaji":["kanai"],"meaning":"one's wife"},
    "しゅじん": {"romaji":["shujin"],"meaning":"one's husband"},
    "あかちゃん": {"romaji":["akachan"],"meaning":"baby"},
    "おとな": {"romaji":["otona"],"meaning":"adult"},
    "わかもの": {"romaji":["wakamono"],"meaning":"young person"},
    "となり": {"romaji":["tonari"],"meaning":"neighbour"},
    "しんせき": {"romaji":["shinseki"],"meaning":"relatives"},
    "いとこ": {"romaji":["itoko"],"meaning":"cousin"},
    "おじさん": {"romaji":["ojisan"],"meaning":"uncle, middle-aged man"},
    "おばさん": {"romaji":["obasan"],"meaning":"aunt, middle-aged woman"},
    "しゃちょう": {"romaji":["shachou"],"meaning":"company president"},
    "がくせい": {"romaji":["gakusei"],"meaning":"student"},
    "せいと": {"romaji":["seito"],"meaning":"pupil"}
  
    },
    "PLACES & TRANSPORT": {
        "こうえん": {"romaji":["kouen"],"meaning":"park"},
        "かいがん": {"romaji":["kaigan"],"meaning":"coast"},
        "くるま": {"romaji":["kuruma"],"meaning":"car"},
        "でんわ": {"romaji":["denwa"],"meaning":"telephone"},
        "がっこう": {"romaji":["gakkou"],"meaning":"school"},
        "えき": {"romaji":["eki"],"meaning":"station"},
        "びょういん": {"romaji":["byouin"],"meaning":"hospital"},
        "ぎんこう": {"romaji":["ginkou"],"meaning":"bank"},
        "としょかん": {"romaji":["toshokan"],"meaning":"library"},
        "ゆうびんきょく": {"romaji":["yuubinkyoku"],"meaning":"post office"},
        "どうぶつえん": {"romaji":["doubutsuen"],"meaning":"zoo"},
        "えいがかん": {"romaji":["eigakan"],"meaning":"movie theater"},
        "きっさてん": {"romaji":["kissaten"],"meaning":"cafe"},
        "でんしゃ": {"romaji":["densha"],"meaning":"train"},
        "じてんしゃ": {"romaji":["jitensha"],"meaning":"bicycle"},
        "ひこうき": {"romaji":["hikouki"],"meaning":"airplane"},
        "ふね": {"romaji":["fune"],"meaning":"ship/boat"},
        "ばす": {"romaji":["basu"],"meaning":"bus"},
        "ちかてつ": {"romaji":["chikatetsu"],"meaning":"subway"},
    "みち": {"romaji":["michi"],"meaning":"road"},
    "こうさてん": {"romaji":["kousaten"],"meaning":"intersection"},
    "しんごう": {"romaji":["shingou"],"meaning":"traffic light"},
    "ちゅうしゃじょう": {"romaji":["chuushajou"],"meaning":"parking lot"},
    "こうじょう": {"romaji":["koujou"],"meaning":"factory"},
    "かいしゃ": {"romaji":["kaisha"],"meaning":"company"},
    "みせ": {"romaji":["mise"],"meaning":"shop"},
    "いちば": {"romaji":["ichiba"],"meaning":"market"},
    "こうばん": {"romaji":["kouban"],"meaning":"police box"},
    "じんじゃ": {"romaji":["jinja"],"meaning":"shrine"},
    "おてら": {"romaji":["otera"],"meaning":"temple"},
    "おしろ": {"romaji":["oshiro"],"meaning":"castle"},
    "たいしかん": {"romaji":["taishikan"],"meaning":"embassy"},
    "せき": {"romaji":["seki"],"meaning":"seat"}
  
    },
    "ADJECTIVES": {
        "あかるい": {"romaji":["akarui"],"meaning":"bright"},
        "しずか": {"romaji":["shizuka"],"meaning":"quiet"},
        "たのしい": {"romaji":["tanoshii"],"meaning":"fun"},
        "うれしい": {"romaji":["ureshii"],"meaning":"happy"},
        "かなしい": {"romaji":["kanashii"],"meaning":"sad"},
        "はやい": {"romaji":["hayai"],"meaning":"fast"},
        "おそい": {"romaji":["osoi"],"meaning":"slow"},
        "あつい": {"romaji":["atsui"],"meaning":"hot/thick"},
        "さむい": {"romaji":["samui"],"meaning":"cold (weather)"},
        "つめたい": {"romaji":["tsumetai"],"meaning":"cold to touch"},
        "きれい": {"romaji":["kirei"],"meaning":"beautiful/clean"},
        "ちいさい": {"romaji":["chiisai"],"meaning":"small"},
        "おおきい": {"romaji":["ookii"],"meaning":"big"},
        "たかい": {"romaji":["takai"],"meaning":"expensive/tall"},
        "やすい": {"romaji":["yasui"],"meaning":"cheap"},
        "あたらしい": {"romaji":["atarashii"],"meaning":"new"},
        "ふるい": {"romaji":["furui"],"meaning":"old"},
        "むずかしい": {"romaji":["muzukashii"],"meaning":"difficult"},
        "やさしい": {"romaji":["yasashii"],"meaning":"easy/kind"},
        "とおい": {"romaji":["tooi"],"meaning":"far"},
        "ちかい": {"romaji":["chikai"],"meaning":"near"},
        "ひろい": {"romaji":["hiroi"],"meaning":"wide"},
        "せまい": {"romaji":["semai"],"meaning":"narrow"},
        "ねむい": {"romaji":["nemui"],"meaning":"sleepy"},
        "つよい": {"romaji":["tsuyoi"],"meaning":"strong"},
        "よわい": {"romaji":["yowai"],"meaning":"weak"},
    "わかい": {"romaji":["wakai"],"meaning":"young"},
    "としより": {"romaji":["toshiyori"],"meaning":"elderly"},
    "ながい": {"romaji":["nagai"],"meaning":"long"},
    "みじかい": {"romaji":["mijikai"],"meaning":"short (length)"},
    "ひくい": {"romaji":["hikui"],"meaning":"low"},
    "おもい": {"romaji":["omoi"],"meaning":"heavy"},
    "かるい": {"romaji":["karui"],"meaning":"light (weight)"},
    "かたい": {"romaji":["katai"],"meaning":"hard"},
    "やわらかい": {"romaji":["yawarakai"],"meaning":"soft"},
    "あたたかい": {"romaji":["atatakai"],"meaning":"warm"},
    "すずしい": {"romaji":["suzushii"],"meaning":"cool"},
    "くらい": {"romaji":["kurai"],"meaning":"dark"},
    "うるさい": {"romaji":["urusai"],"meaning":"noisy"},
    "いそがしい": {"romaji":["isogashii"],"meaning":"busy"},
    "ひま": {"romaji":["hima"],"meaning":"free time"},
    "げんき": {"romaji":["genki"],"meaning":"energetic, well"},
    "あぶない": {"romaji":["abunai"],"meaning":"dangerous"},
    "あんぜん": {"romaji":["anzen"],"meaning":"safe"},
    "べんり": {"romaji":["benri"],"meaning":"convenient"},
    "ふべん": {"romaji":["fuben"],"meaning":"inconvenient"},
    "ゆうめい": {"romaji":["yuumei"],"meaning":"famous"},
    "たいせつ": {"romaji":["taisetsu"],"meaning":"important, precious"},
    "いろいろ": {"romaji":["iroiro"],"meaning":"various"},
    "おなじ": {"romaji":["onaji"],"meaning":"same"},
    "ちがう": {"romaji":["chigau"],"meaning":"different, wrong"}
  
    },
    "TIME & MISC": {
        "あした": {"romaji":["ashita"],"meaning":"tomorrow"},
        "きのう": {"romaji":["kinou"],"meaning":"yesterday"},
        "きょう": {"romaji":["kyou"],"meaning":"today"},
        "あさ": {"romaji":["asa"],"meaning":"morning"},
        "よる": {"romaji":["yoru"],"meaning":"night"},
        "ひる": {"romaji":["hiru"],"meaning":"daytime"},
        "せかい": {"romaji":["sekai"],"meaning":"world"},
    "いま": {"romaji":["ima"],"meaning":"now"},
    "あとで": {"romaji":["atode"],"meaning":"later"},
    "さっき": {"romaji":["sakki"],"meaning":"a moment ago"},
    "まいにち": {"romaji":["mainichi"],"meaning":"every day"},
    "まいあさ": {"romaji":["maiasa"],"meaning":"every morning"},
    "まいばん": {"romaji":["maiban"],"meaning":"every evening"},
    "ひごろ": {"romaji":["higoro"],"meaning":"usually"},
    "しゅうまつ": {"romaji":["shuumatsu"],"meaning":"weekend"},
    "こんしゅう": {"romaji":["konshuu"],"meaning":"this week"},
    "らいしゅう": {"romaji":["raishuu"],"meaning":"next week"},
    "せんしゅう": {"romaji":["senshuu"],"meaning":"last week"},
    "こんげつ": {"romaji":["kongetsu"],"meaning":"this month"},
    "らいねん": {"romaji":["rainen"],"meaning":"next year"},
    "きょねん": {"romaji":["kyonen"],"meaning":"last year"},
    "ことし": {"romaji":["kotoshi"],"meaning":"this year"},
    "じかん": {"romaji":["jikan"],"meaning":"time, hour"},
    "ふん": {"romaji":["fun"],"meaning":"minute"},
    "びょう": {"romaji":["byou"],"meaning":"second"},
    "いつも": {"romaji":["itsumo"],"meaning":"always"},
    "ときどき": {"romaji":["tokidoki"],"meaning":"sometimes"}
  
    },
    "COLORS": {
        "あか": {"romaji":["aka"],"meaning":"red"},
        "あお": {"romaji":["ao"],"meaning":"blue"},
        "しろ": {"romaji":["shiro"],"meaning":"white"},
        "くろ": {"romaji":["kuro"],"meaning":"black"},
        "きいろ": {"romaji":["kiiro"],"meaning":"yellow"},
        "みどり": {"romaji":["midori"],"meaning":"green"},
        "ちゃいろ": {"romaji":["chairo"],"meaning":"brown"},
        "むらさき": {"romaji":["murasaki"],"meaning":"purple"},
    "ももいろ": {"romaji":["momoiro"],"meaning":"pink"},
    "そらいろ": {"romaji":["sorairo"],"meaning":"sky blue"},
    "はいいろ": {"romaji":["haiiro"],"meaning":"grey"},
    "こんいろ": {"romaji":["kon'iro"],"meaning":"navy blue"},
    "きんいろ": {"romaji":["kin'iro"],"meaning":"gold"},
    "ぎんいろ": {"romaji":["gin'iro"],"meaning":"silver"},
    "だいだいいろ": {"romaji":["daidaiiro"],"meaning":"orange"}
  
    },
    "NUMBERS": {
        "いち": {"romaji":["ichi"],"meaning":"one"},
        "に": {"romaji":["ni"],"meaning":"two"},
        "さん": {"romaji":["san"],"meaning":"three"},
        "よん": {"romaji":["yon"],"meaning":"four"},
        "ご": {"romaji":["go"],"meaning":"five"},
        "ろく": {"romaji":["roku"],"meaning":"six"},
        "なな": {"romaji":["nana"],"meaning":"seven"},
        "はち": {"romaji":["hachi"],"meaning":"eight"},
        "きゅう": {"romaji":["kyuu"],"meaning":"nine"},
        "じゅう": {"romaji":["juu"],"meaning":"ten"},
    "ぜろ": {"romaji":["zero"],"meaning":"zero"},
    "ひゃく": {"romaji":["hyaku"],"meaning":"hundred"},
    "せん": {"romaji":["sen"],"meaning":"thousand"},
    "まん": {"romaji":["man"],"meaning":"ten thousand"},
    "にじゅう": {"romaji":["nijuu"],"meaning":"twenty"},
    "さんじゅう": {"romaji":["sanjuu"],"meaning":"thirty"},
    "ごじゅう": {"romaji":["gojuu"],"meaning":"fifty"},
    "はんぶん": {"romaji":["hanbun"],"meaning":"half"}
  
    },
    "COUNTERS": {
        "ひとつ": {"romaji":["hitotsu"],"meaning":"one (object)"},
        "ふたつ": {"romaji":["futatsu"],"meaning":"two (objects)"},
        "みっつ": {"romaji":["mittsu"],"meaning":"three (objects)"},
        "よっつ": {"romaji":["yottsu"],"meaning":"four (objects)"},
        "いつつ": {"romaji":["itsutsu"],"meaning":"five (objects)"},
        "むっつ": {"romaji":["muttsu"],"meaning":"six (objects)"},
        "ななつ": {"romaji":["nanatsu"],"meaning":"seven (objects)"},
        "やっつ": {"romaji":["yattsu"],"meaning":"eight (objects)"},
        "ここのつ": {"romaji":["kokonotsu"],"meaning":"nine (objects)"},
        "とお": {"romaji":["too"],"meaning":"ten (objects)"},
        "いくつ": {"romaji":["ikutsu"],"meaning":"how many?"},
    "いちまい": {"romaji":["ichimai"],"meaning":"one (flat object)"},
    "にまい": {"romaji":["nimai"],"meaning":"two (flat objects)"},
    "いちにん": {"romaji":["ichinin"],"meaning":"one person"},
    "ふたり": {"romaji":["futari"],"meaning":"two people"},
    "さんにん": {"romaji":["sannin"],"meaning":"three people"},
    "いっぴき": {"romaji":["ippiki"],"meaning":"one (small animal)"},
    "にひき": {"romaji":["nihiki"],"meaning":"two (small animals)"},
    "いっさつ": {"romaji":["issatsu"],"meaning":"one (book)"},
    "にさつ": {"romaji":["nisatsu"],"meaning":"two (books)"},
    "いっぽん": {"romaji":["ippon"],"meaning":"one (long object)"},
    "にほん": {"romaji":["nihon"],"meaning":"two (long objects)"},
    "いっかい": {"romaji":["ikkai"],"meaning":"once, first floor"},
    "にかい": {"romaji":["nikai"],"meaning":"twice, second floor"}
  
    },
    "VERBS": {
        "たべる": {"romaji":["taberu"],"meaning":"to eat"},
        "のむ": {"romaji":["nomu"],"meaning":"to drink"},
        "ねる": {"romaji":["neru"],"meaning":"to sleep"},
        "おきる": {"romaji":["okiru"],"meaning":"to wake up"},
        "いく": {"romaji":["iku"],"meaning":"to go"},
        "くる": {"romaji":["kuru"],"meaning":"to come"},
        "かえる": {"romaji":["kaeru"],"meaning":"to return home"},
        "みる": {"romaji":["miru"],"meaning":"to see/watch"},
        "きく": {"romaji":["kiku"],"meaning":"to listen"},
        "かく": {"romaji":["kaku"],"meaning":"to write"},
        "よむ": {"romaji":["yomu"],"meaning":"to read"},
        "はなす": {"romaji":["hanasu"],"meaning":"to speak"},
        "かう": {"romaji":["kau"],"meaning":"to buy"},
        "あそぶ": {"romaji":["asobu"],"meaning":"to play"},
    "はしる": {"romaji":["hashiru"],"meaning":"to run"},
    "あるく": {"romaji":["aruku"],"meaning":"to walk"},
    "およぐ": {"romaji":["oyogu"],"meaning":"to swim"},
    "とぶ": {"romaji":["tobu"],"meaning":"to fly, to jump"},
    "すわる": {"romaji":["suwaru"],"meaning":"to sit"},
    "たつ": {"romaji":["tatsu"],"meaning":"to stand"},
    "わらう": {"romaji":["warau"],"meaning":"to laugh"},
    "なく": {"romaji":["naku"],"meaning":"to cry"},
    "おこる": {"romaji":["okoru"],"meaning":"to get angry"},
    "あける": {"romaji":["akeru"],"meaning":"to open"},
    "しめる": {"romaji":["shimeru"],"meaning":"to close"},
    "いれる": {"romaji":["ireru"],"meaning":"to put in"},
    "だす": {"romaji":["dasu"],"meaning":"to take out"},
    "つける": {"romaji":["tsukeru"],"meaning":"to turn on"},
    "けす": {"romaji":["kesu"],"meaning":"to turn off, erase"},
    "まつ": {"romaji":["matsu"],"meaning":"to wait"},
    "つかう": {"romaji":["tsukau"],"meaning":"to use"},
    "つくる": {"romaji":["tsukuru"],"meaning":"to make"},
    "あらう": {"romaji":["arau"],"meaning":"to wash"},
    "そうじする": {"romaji":["soujisuru"],"meaning":"to clean"},
    "はたらく": {"romaji":["hataraku"],"meaning":"to work"},
    "やすむ": {"romaji":["yasumu"],"meaning":"to rest"},
    "わかる": {"romaji":["wakaru"],"meaning":"to understand"},
    "しる": {"romaji":["shiru"],"meaning":"to know"},
    "わすれる": {"romaji":["wasureru"],"meaning":"to forget"},
    "おぼえる": {"romaji":["oboeru"],"meaning":"to remember"},
    "おしえる": {"romaji":["oshieru"],"meaning":"to teach"},
    "ならう": {"romaji":["narau"],"meaning":"to learn"},
    "えらぶ": {"romaji":["erabu"],"meaning":"to choose"},
    "さがす": {"romaji":["sagasu"],"meaning":"to search for"}
  
    },
  "EMOTIONS & FEELINGS": {
    "しあわせ": {"romaji":["shiawase"],"meaning":"happiness"},
    "さびしい": {"romaji":["sabishii"],"meaning":"lonely"},
    "こわい": {"romaji":["kowai"],"meaning":"scary, afraid"},
    "びっくり": {"romaji":["bikkuri"],"meaning":"surprised"},
    "すき": {"romaji":["suki"],"meaning":"like, favourite"},
    "だいすき": {"romaji":["daisuki"],"meaning":"love, really like"},
    "きらい": {"romaji":["kirai"],"meaning":"dislike"},
    "だいきらい": {"romaji":["daikirai"],"meaning":"hate"},
    "はずかしい": {"romaji":["hazukashii"],"meaning":"embarrassed"},
    "しんぱい": {"romaji":["shinpai"],"meaning":"worry"},
    "あんしん": {"romaji":["anshin"],"meaning":"peace of mind"},
    "たのしみ": {"romaji":["tanoshimi"],"meaning":"looking forward to"},
    "ゆめ": {"romaji":["yume"],"meaning":"dream"},
    "きぼう": {"romaji":["kibou"],"meaning":"hope"},
    "きもち": {"romaji":["kimochi"],"meaning":"feeling"},
    "あいする": {"romaji":["aisuru"],"meaning":"to love"},
    "いや": {"romaji":["iya"],"meaning":"unpleasant, no"},
    "だめ": {"romaji":["dame"],"meaning":"no good, useless"}
  },
  "GREETINGS & PHRASES": {
    "こんにちは": {"romaji":["konnichiwa"],"meaning":"hello, good afternoon"},
    "おはよう": {"romaji":["ohayou"],"meaning":"good morning"},
    "こんばんは": {"romaji":["konbanwa"],"meaning":"good evening"},
    "おやすみ": {"romaji":["oyasumi"],"meaning":"good night"},
    "さようなら": {"romaji":["sayounara"],"meaning":"goodbye"},
    "ありがとう": {"romaji":["arigatou"],"meaning":"thank you"},
    "どういたしまして": {"romaji":["douitashimashite"],"meaning":"you're welcome"},
    "すみません": {"romaji":["sumimasen"],"meaning":"excuse me, sorry"},
    "ごめんなさい": {"romaji":["gomennasai"],"meaning":"I'm sorry"},
    "はじめまして": {"romaji":["hajimemashite"],"meaning":"nice to meet you"},
    "おねがいします": {"romaji":["onegaishimasu"],"meaning":"please"},
    "いただきます": {"romaji":["itadakimasu"],"meaning":"(said before eating)"},
    "ごちそうさま": {"romaji":["gochisousama"],"meaning":"(said after eating)"},
    "いってきます": {"romaji":["ittekimasu"],"meaning":"I'm off"},
    "いってらっしゃい": {"romaji":["itterasshai"],"meaning":"see you (to someone leaving)"},
    "ただいま": {"romaji":["tadaima"],"meaning":"I'm home"},
    "おかえり": {"romaji":["okaeri"],"meaning":"welcome home"},
    "がんばって": {"romaji":["ganbatte"],"meaning":"do your best"},
    "だいじょうぶ": {"romaji":["daijoubu"],"meaning":"OK, all right"},
    "もちろん": {"romaji":["mochiron"],"meaning":"of course"}
  },
  "SOUNDS & ONOMATOPOEIA": {
    "わんわん": {"romaji":["wanwan"],"meaning":"woof (dog)"},
    "にゃんにゃん": {"romaji":["nyannyan"],"meaning":"meow (cat)"},
    "こけこっこう": {"romaji":["kokekokkou"],"meaning":"cock-a-doodle-doo"},
    "かあかあ": {"romaji":["kaakaa"],"meaning":"caw (crow)"},
    "ぶうぶう": {"romaji":["buubuu"],"meaning":"oink (pig)"},
    "もうもう": {"romaji":["moumou"],"meaning":"moo (cow)"},
    "ぴかぴか": {"romaji":["pikapika"],"meaning":"sparkling"},
    "きらきら": {"romaji":["kirakira"],"meaning":"glittering, twinkling"},
    "ふわふわ": {"romaji":["fuwafuwa"],"meaning":"fluffy"},
    "さらさら": {"romaji":["sarasara"],"meaning":"smooth, silky"},
    "べたべた": {"romaji":["betabeta"],"meaning":"sticky"},
    "ざあざあ": {"romaji":["zaazaa"],"meaning":"heavy rain"},
    "しとしと": {"romaji":["shitoshito"],"meaning":"drizzling"},
    "ごろごろ": {"romaji":["gorogoro"],"meaning":"thunder rumbling"},
    "にこにこ": {"romaji":["nikoniko"],"meaning":"smiling"},
    "わくわく": {"romaji":["wakuwaku"],"meaning":"excited"},
    "どきどき": {"romaji":["dokidoki"],"meaning":"heart pounding"},
    "ぺこぺこ": {"romaji":["pekopeko"],"meaning":"hungry (stomach)"},
    "ぐっすり": {"romaji":["gussuri"],"meaning":"sound asleep"},
    "ゆっくり": {"romaji":["yukkuri"],"meaning":"slowly, leisurely"}
  },
  "SCHOOL & LEARNING": {
    "べんきょう": {"romaji":["benkyou"],"meaning":"study"},
    "しゅくだい": {"romaji":["shukudai"],"meaning":"homework"},
    "じゅぎょう": {"romaji":["jugyou"],"meaning":"class, lesson"},
    "きょうしつ": {"romaji":["kyoushitsu"],"meaning":"classroom"},
    "こくばん": {"romaji":["kokuban"],"meaning":"blackboard"},
    "けしごむ": {"romaji":["keshigomu"],"meaning":"eraser"},
    "ものさし": {"romaji":["monosashi"],"meaning":"ruler"},
    "ちょうさ": {"romaji":["chousa"],"meaning":"investigation"},
    "しつもん": {"romaji":["shitsumon"],"meaning":"question"},
    "こたえ": {"romaji":["kotae"],"meaning":"answer"},
    "せいかい": {"romaji":["seikai"],"meaning":"correct answer"},
    "まちがい": {"romaji":["machigai"],"meaning":"mistake"},
    "えんそく": {"romaji":["ensoku"],"meaning":"school excursion"},
    "なつやすみ": {"romaji":["natsuyasumi"],"meaning":"summer vacation"},
    "ふゆやすみ": {"romaji":["fuyuyasumi"],"meaning":"winter vacation"},
    "そつぎょう": {"romaji":["sotsugyou"],"meaning":"graduation"},
    "にゅうがく": {"romaji":["nyuugaku"],"meaning":"school entrance"},
    "せいふく": {"romaji":["seifuku"],"meaning":"school uniform"},
    "なまえ": {"romaji":["namae"],"meaning":"name"}
  },
  "CLOTHING": {
    "ふく": {"romaji":["fuku"],"meaning":"clothes"},
    "ようふく": {"romaji":["youfuku"],"meaning":"Western clothes"},
    "きもの": {"romaji":["kimono"],"meaning":"kimono"},
    "じんべい": {"romaji":["jinbei"],"meaning":"summer kimono"},
    "したぎ": {"romaji":["shitagi"],"meaning":"underwear"},
    "うわぎ": {"romaji":["uwagi"],"meaning":"jacket, coat"},
    "ゆびわ": {"romaji":["yubiwa"],"meaning":"ring"},
    "うでどけい": {"romaji":["udedokei"],"meaning":"wristwatch"},
    "かみかざり": {"romaji":["kamikazari"],"meaning":"hair ornament"},
    "えりまき": {"romaji":["erimaki"],"meaning":"scarf"}
  },
  "DIRECTIONS & POSITIONS": {
    "うえ": {"romaji":["ue"],"meaning":"up, above"},
    "まえ": {"romaji":["mae"],"meaning":"front, before"},
    "うしろ": {"romaji":["ushiro"],"meaning":"behind"},
    "みぎ": {"romaji":["migi"],"meaning":"right"},
    "ひだり": {"romaji":["hidari"],"meaning":"left"},
    "あいだ": {"romaji":["aida"],"meaning":"between"},
    "そば": {"romaji":["soba"],"meaning":"beside, near"},
    "なか": {"romaji":["naka"],"meaning":"inside, middle"},
    "そと": {"romaji":["soto"],"meaning":"outside"},
    "きた": {"romaji":["kita"],"meaning":"north"},
    "みなみ": {"romaji":["minami"],"meaning":"south"},
    "ひがし": {"romaji":["higashi"],"meaning":"east"},
    "にし": {"romaji":["nishi"],"meaning":"west"},
    "ここ": {"romaji":["koko"],"meaning":"here"},
    "そこ": {"romaji":["soko"],"meaning":"there"},
    "あそこ": {"romaji":["asoko"],"meaning":"over there"},
    "どこ": {"romaji":["doko"],"meaning":"where"},
    "むこう": {"romaji":["mukou"],"meaning":"the other side"}
  }
};
