const KATAKANA_VOCAB_DATA = {
  "Vocabulary (Katakana)": {
    "カメラ": {"romaji":["kamera"],"meaning":"camera"},
    "テレビ": {"romaji":["terebi"],"meaning":"TV"},
    "ラジオ": {"romaji":["rajio"],"meaning":"radio"},
    "パソコン": {"romaji":["pasokon"],"meaning":"PC/laptop"},
    "スマホ": {"romaji":["sumaho"],"meaning":"smartphone"},
    "エアコン": {"romaji":["eakon"],"meaning":"air conditioner"},
    "ビデオ": {"romaji":["bideo"],"meaning":"video"},
    "リモコン": {"romaji":["rimokon"],"meaning":"remote control"},
    "インターネット": {"romaji":["intaanetto"],"meaning":"internet"},
    "コーヒー": {"romaji":["ko-hi-","koohi","koohii","kohi"],"meaning":"coffee"},
    "コーラ": {"romaji":["ko-ra","koora","kora"],"meaning":"cola"},
    "ビール": {"romaji":["bi-ru","biiru","biru"],"meaning":"beer"},
    "ワイン": {"romaji":["wain"],"meaning":"wine"},
    "パン": {"romaji":["pan"],"meaning":"bread"},
    "ケーキ": {"romaji":["ke-ki","keeki","keki"],"meaning":"cake"},
    "アイス": {"romaji":["aisu"],"meaning":"ice cream"},
    "サラダ": {"romaji":["sarada"],"meaning":"salad"},
    "チーズ": {"romaji":["chi-zu","chiizu","chizu"],"meaning":"cheese"},
    "パスタ": {"romaji":["pasuta"],"meaning":"pasta"},
    "メニュー": {"romaji":["menyu-","menyuu","menyu"],"meaning":"menu"},
    "ジュース": {"romaji":["ju-su","juusu","jusu"],"meaning":"juice"},
    "ハンバーグ": {"romaji":["hanba-gu"],"meaning":"hamburger steak"},
    "ピザ": {"romaji":["piza"],"meaning":"pizza"},
    "サンドイッチ": {"romaji":["sandoitchi"],"meaning":"sandwich"},
    "チョコレート": {"romaji":["chokore-to"],"meaning":"chocolate"},
    "カレー": {"romaji":["kare-"],"meaning":"curry"},
    "スープ": {"romaji":["su-pu"],"meaning":"soup"},
    "バナナ": {"romaji":["banana"],"meaning":"banana"},
    "オレンジ": {"romaji":["orenji"],"meaning":"orange"},
    "リンゴ": {"romaji":["ringo"],"meaning":"apple (often katakana)"},
    "メロン": {"romaji":["meron"],"meaning":"melon"},
    "パイナップル": {"romaji":["painappuru"],"meaning":"pineapple"},
    "トマト": {"romaji":["tomato"],"meaning":"tomato"},
    "キャベツ": {"romaji":["kyabetsu"],"meaning":"cabbage"},
    "レタス": {"romaji":["retasu"],"meaning":"lettuce"},
    "ドア": {"romaji":["doa"],"meaning":"door"},
    "ノート": {"romaji":["no-to","nooto","noto"],"meaning":"notebook"},
    "ペン": {"romaji":["pen"],"meaning":"pen"},
    "ボールペン": {"romaji":["bo-rupen","boorupen"],"meaning":"ballpoint pen"},
    "サンダル": {"romaji":["sandaru"],"meaning":"sandals"},
    "ハンカチ": {"romaji":["hankachi"],"meaning":"handkerchief"},
    "フォーク": {"romaji":["fo-ku","fooku","foku"],"meaning":"fork"},
    "ナイフ": {"romaji":["naifu"],"meaning":"knife"},
    "スプーン": {"romaji":["supu-n","supuun","supun"],"meaning":"spoon"},
    "コップ": {"romaji":["koppu"],"meaning":"glass/cup"},
    "キッチン": {"romaji":["kitchin"],"meaning":"kitchen"},
    "ベッド": {"romaji":["beddo"],"meaning":"bed"},
    "ソファ": {"romaji":["sofa"],"meaning":"sofa"},
    "シャワー": {"romaji":["shawa-","shawaa","shawa"],"meaning":"shower"},
    "カレンダー": {"romaji":["karenda-","karendaa"],"meaning":"calendar"},
    "テーブル": {"romaji":["te-buru"],"meaning":"table"},
    "カーテン": {"romaji":["ka-ten"],"meaning":"curtain"},
    "タンス": {"romaji":["tansu"],"meaning":"chest of drawers"},
    "タオル": {"romaji":["taoru"],"meaning":"towel"},
    "ブラシ": {"romaji":["burashi"],"meaning":"brush"},
    "シャツ": {"romaji":["shatsu"],"meaning":"shirt"},
    "ズボン": {"romaji":["zubon"],"meaning":"pants"},
    "ネクタイ": {"romaji":["nekutai"],"meaning":"necktie"},
    "スカート": {"romaji":["suka-to"],"meaning":"skirt"},
    "コート": {"romaji":["ko-to"],"meaning":"coat"},
    "セーター": {"romaji":["se-ta-"],"meaning":"sweater"},
    "ドレス": {"romaji":["doresu"],"meaning":"dress"},
    "ワンピース": {"romaji":["wanpi-su"],"meaning":"one-piece dress"},
    "ホテル": {"romaji":["hoteru"],"meaning":"hotel"},
    "トイレ": {"romaji":["toire"],"meaning":"toilet/bathroom"},
    "ビル": {"romaji":["biru"],"meaning":"building"},
    "レストラン": {"romaji":["resutoran"],"meaning":"restaurant"},
    "デパート": {"romaji":["depa-to","depaato","depato"],"meaning":"department store"},
    "エレベーター": {"romaji":["erebe-ta-","erebeetaa"],"meaning":"elevator"},
    "スーパー": {"romaji":["su-pa-"],"meaning":"supermarket"},
    "コンビニ": {"romaji":["konbini"],"meaning":"convenience store"},
    "プール": {"romaji":["pu-ru"],"meaning":"pool"},
    "アパート": {"romaji":["apa-to"],"meaning":"apartment"},
    "タクシー": {"romaji":["takushi-","takushii","takushi"],"meaning":"taxi"},
    "バス": {"romaji":["basu"],"meaning":"bus"},
    "トラック": {"romaji":["torakku"],"meaning":"truck"},
    "オートバイ": {"romaji":["ootobai"],"meaning":"motorcycle"},
    "エンジン": {"romaji":["enjin"],"meaning":"engine"},
    "テニス": {"romaji":["tenisu"],"meaning":"tennis"},
    "サッカー": {"romaji":["sakka-","sakkaa","sakka"],"meaning":"soccer"},
    "ピアノ": {"romaji":["piano"],"meaning":"piano"},
    "ギター": {"romaji":["gita-","gitaa","gita"],"meaning":"guitar"},
    "スポーツ": {"romaji":["supo-tsu","supootsu"],"meaning":"sports"},
    "ダンス": {"romaji":["dansu"],"meaning":"dance"},
    "ドラム": {"romaji":["doramu"],"meaning":"drums"},
    "ゴルフ": {"romaji":["gorufu"],"meaning":"golf"},
    "スキー": {"romaji":["suki-"],"meaning":"skiing"},
    "ジャズ": {"romaji":["jazu"],"meaning":"jazz"},
    "アメリカ": {"romaji":["amerika"],"meaning":"USA"},
    "イギリス": {"romaji":["igirisu"],"meaning":"UK"},
    "フランス": {"romaji":["furansu"],"meaning":"France"},
    "ドイツ": {"romaji":["doitsu"],"meaning":"Germany"},
    "イタリア": {"romaji":["itaria"],"meaning":"Italy"},
    "スペイン": {"romaji":["supein"],"meaning":"Spain"},
    "カナダ": {"romaji":["kanada"],"meaning":"Canada"},
    "オーストラリア": {"romaji":["oosutoraria"],"meaning":"Australia"},
    "ロシア": {"romaji":["roshia"],"meaning":"Russia"},
    "アジア": {"romaji":["ajia"],"meaning":"Asia"},
    "ヨーロッパ": {"romaji":["yo-roppa"],"meaning":"Europe"},
    "エンジニア": {"romaji":["enjinia"],"meaning":"engineer"},
    "デザイナー": {"romaji":["dezaina-"],"meaning":"designer"},
    "パイロット": {"romaji":["pairotto"],"meaning":"pilot"},
    "サラリーマン": {"romaji":["sarari-man"],"meaning":"office worker"},
    "モデル": {"romaji":["moderu"],"meaning":"model"},
    "ニュース": {"romaji":["nyu-su","nyuusu","nyusu"],"meaning":"news"},
    "プレゼント": {"romaji":["purezento"],"meaning":"present"},
    "クラス": {"romaji":["kurasu"],"meaning":"class"},
    "チケット": {"romaji":["chiketto"],"meaning":"ticket"},
    "ネコ": {"romaji":["neko"],"meaning":"cat (often katakana)"},
    "ルール": {"romaji":["ru-ru"],"meaning":"rule"},
    "チャンス": {"romaji":["chansu"],"meaning":"chance"},
    "サービス": {"romaji":["sa-bisu"],"meaning":"service"},
    "メッセージ": {"romaji":["messe-ji"],"meaning":"message"},
    "ページ": {"romaji":["pe-ji"],"meaning":"page"},
    "カー": {"romaji":["ka-","kaa"],"meaning":"car"},
    "ヘリコプター": {"romaji":["herikoputa-"],"meaning":"helicopter"},
    "フェリー": {"romaji":["feri-"],"meaning":"ferry"},
    "スクーター": {"romaji":["suku-ta-"],"meaning":"scooter"},
    "リムジン": {"romaji":["rimujin"],"meaning":"limousine"},
    "ロケット": {"romaji":["roketto"],"meaning":"rocket"},
    "タンカー": {"romaji":["tanka-"],"meaning":"tanker"},
    "ドクター": {"romaji":["dokuta-"],"meaning":"doctor"},
    "ナース": {"romaji":["na-su"],"meaning":"nurse"},
    "シェフ": {"romaji":["shefu"],"meaning":"chef"},
    "アーティスト": {"romaji":["a-tisuto"],"meaning":"artist"},
    "ジャーナリスト": {"romaji":["ja-narisuto"],"meaning":"journalist"},
    "プログラマー": {"romaji":["purograma-"],"meaning":"programmer"},
    "マネージャー": {"romaji":["mane-ja-"],"meaning":"manager"},
    "マンゴー": {"romaji":["mango-"],"meaning":"mango"},
    "ブドウ": {"romaji":["budou"],"meaning":"grapes"},
    "イチゴ": {"romaji":["ichigo"],"meaning":"strawberry"},
    "ブロッコリー": {"romaji":["burokori-"],"meaning":"broccoli"},
    "ニンジン": {"romaji":["ninjin"],"meaning":"carrot"},
    "タマネギ": {"romaji":["tamanegi"],"meaning":"onion"},
    "スイカ": {"romaji":["suika"],"meaning":"watermelon"},
    "ジャケット": {"romaji":["jaketto"],"meaning":"jacket"},
    "ブーツ": {"romaji":["bu-tsu"],"meaning":"boots"},
    "スニーカー": {"romaji":["suni-ka-"],"meaning":"sneakers"},
    "マフラー": {"romaji":["mafura-"],"meaning":"scarf"},
    "グローブ": {"romaji":["guro-bu"],"meaning":"gloves"},
    "ベルト": {"romaji":["beruto"],"meaning":"belt"},
    "キャップ": {"romaji":["kyappu"],"meaning":"cap"},
    "マイク": {"romaji":["maiku"],"meaning":"microphone"},
    "スピーカー": {"romaji":["supiikaa"],"meaning":"speaker"},
    "イヤホン": {"romaji":["iyahon"],"meaning":"earphones"},
    "ヘッドホン": {"romaji":["heddohon"],"meaning":"headphones"},
    "プリンター": {"romaji":["purintaa"],"meaning":"printer"},
    "スキャナー": {"romaji":["sukyanaa"],"meaning":"scanner"},
    "モニター": {"romaji":["monitaa"],"meaning":"monitor"},
    "キーボード": {"romaji":["kiiboodo"],"meaning":"keyboard"},
    "マウス": {"romaji":["mausu"],"meaning":"mouse (computer)"},
    "バッテリー": {"romaji":["batterii"],"meaning":"battery"},
    "チャージャー": {"romaji":["chaajaa"],"meaning":"charger"},
    "ケーブル": {"romaji":["keeburu"],"meaning":"cable"},
    "アプリ": {"romaji":["apuri"],"meaning":"app"},
    "ソフト": {"romaji":["sofuto"],"meaning":"software"},
    "データ": {"romaji":["deeta"],"meaning":"data"},
    "ファイル": {"romaji":["fairu"],"meaning":"file"},
    "メール": {"romaji":["meeru"],"meaning":"email"},
    "パスワード": {"romaji":["pasuwaado"],"meaning":"password"},
    "ロボット": {"romaji":["robotto"],"meaning":"robot"},
    "ドローン": {"romaji":["doroon"],"meaning":"drone"},
    "ミルク": {"romaji":["miruku"],"meaning":"milk"},
    "ティー": {"romaji":["tii"],"meaning":"tea"},
    "ミルクティー": {"romaji":["mirukutii"],"meaning":"milk tea"},
    "レモネード": {"romaji":["remoneedo"],"meaning":"lemonade"},
    "スムージー": {"romaji":["sumuujii"],"meaning":"smoothie"},
    "シェイク": {"romaji":["sheiku"],"meaning":"milkshake"},
    "カクテル": {"romaji":["kakuteru"],"meaning":"cocktail"},
    "ウイスキー": {"romaji":["uisukii"],"meaning":"whiskey"},
    "シャンパン": {"romaji":["shanpan"],"meaning":"champagne"},
    "ヨーグルト": {"romaji":["yooguruto"],"meaning":"yoghurt"},
    "バター": {"romaji":["bataa"],"meaning":"butter"},
    "ヨーグルトドリンク": {"romaji":["yoogurutodorinku"],"meaning":"yoghurt drink"},
    "トースト": {"romaji":["toosuto"],"meaning":"toast"},
    "クッキー": {"romaji":["kukkii"],"meaning":"cookie"},
    "ドーナツ": {"romaji":["doonatsu"],"meaning":"doughnut"},
    "プリン": {"romaji":["purin"],"meaning":"pudding"},
    "マフィン": {"romaji":["mafin"],"meaning":"muffin"},
    "ワッフル": {"romaji":["waffuru"],"meaning":"waffle"},
    "パンケーキ": {"romaji":["pankeeki"],"meaning":"pancake"},
    "ハンバーガー": {"romaji":["hanbaagaa"],"meaning":"hamburger"},
    "ホットドッグ": {"romaji":["hottodoggu"],"meaning":"hot dog"},
    "フライドポテト": {"romaji":["furaidopoteto"],"meaning":"french fries"},
    "スパゲッティ": {"romaji":["supagetti"],"meaning":"spaghetti"},
    "ラザニア": {"romaji":["razania"],"meaning":"lasagna"},
    "リゾット": {"romaji":["rizotto"],"meaning":"risotto"},
    "ステーキ": {"romaji":["suteeki"],"meaning":"steak"},
    "ソーセージ": {"romaji":["sooseeji"],"meaning":"sausage"},
    "ベーコン": {"romaji":["beekon"],"meaning":"bacon"},
    "ハム": {"romaji":["hamu"],"meaning":"ham"},
    "マヨネーズ": {"romaji":["mayoneezu"],"meaning":"mayonnaise"},
    "ケチャップ": {"romaji":["kechappu"],"meaning":"ketchup"},
    "ソース": {"romaji":["soosu"],"meaning":"sauce"},
    "スパイス": {"romaji":["supaisu"],"meaning":"spice"},
    "ハーブ": {"romaji":["haabu"],"meaning":"herb"},
    "キウイ": {"romaji":["kiui"],"meaning":"kiwi"},
    "グレープフルーツ": {"romaji":["gureepufuruutsu"],"meaning":"grapefruit"},
    "レモン": {"romaji":["remon"],"meaning":"lemon"},
    "ライム": {"romaji":["raimu"],"meaning":"lime"},
    "チェリー": {"romaji":["cherii"],"meaning":"cherry"},
    "ラズベリー": {"romaji":["razuberii"],"meaning":"raspberry"},
    "ブルーベリー": {"romaji":["buruuberii"],"meaning":"blueberry"},
    "ピーチ": {"romaji":["piichi"],"meaning":"peach"},
    "プラム": {"romaji":["puramu"],"meaning":"plum"},
    "ココナッツ": {"romaji":["kokonattsu"],"meaning":"coconut"},
    "アボカド": {"romaji":["abokado"],"meaning":"avocado"},
    "パパイヤ": {"romaji":["papaiya"],"meaning":"papaya"},
    "ピーマン": {"romaji":["piiman"],"meaning":"green pepper"},
    "パプリカ": {"romaji":["papurika"],"meaning":"paprika, bell pepper"},
    "マッシュルーム": {"romaji":["masshuruumu"],"meaning":"mushroom"},
    "アスパラガス": {"romaji":["asuparagasu"],"meaning":"asparagus"},
    "セロリ": {"romaji":["serori"],"meaning":"celery"},
    "パセリ": {"romaji":["paseri"],"meaning":"parsley"},
    "スパイナッチ": {"romaji":["supainacchi"],"meaning":"spinach"},
    "ズッキーニ": {"romaji":["zukkiini"],"meaning":"zucchini"},
    "カップ": {"romaji":["kappu"],"meaning":"cup"},
    "マグカップ": {"romaji":["magukappu"],"meaning":"mug"},
    "プレート": {"romaji":["pureeto"],"meaning":"plate"},
    "ボウル": {"romaji":["bouru"],"meaning":"bowl"},
    "ポット": {"romaji":["potto"],"meaning":"pot, teapot"},
    "フライパン": {"romaji":["furaipan"],"meaning":"frying pan"},
    "オーブン": {"romaji":["oobun"],"meaning":"oven"},
    "トースター": {"romaji":["toosutaa"],"meaning":"toaster"},
    "ミキサー": {"romaji":["mikisaa"],"meaning":"blender"},
    "レンジ": {"romaji":["renji"],"meaning":"microwave, stove"},
    "シンク": {"romaji":["shinku"],"meaning":"sink"},
    "バスタブ": {"romaji":["basutabu"],"meaning":"bathtub"},
    "シャンプー": {"romaji":["shanpuu"],"meaning":"shampoo"},
    "リンス": {"romaji":["rinsu"],"meaning":"conditioner"},
    "ソープ": {"romaji":["soopu"],"meaning":"soap"},
    "ティッシュ": {"romaji":["tisshu"],"meaning":"tissue"},
    "トイレットペーパー": {"romaji":["toirettopeepaa"],"meaning":"toilet paper"},
    "ゴミ": {"romaji":["gomi"],"meaning":"garbage"},
    "バケツ": {"romaji":["baketsu"],"meaning":"bucket"},
    "ハンガー": {"romaji":["hangaa"],"meaning":"hanger"},
    "クッション": {"romaji":["kusshon"],"meaning":"cushion"},
    "ブランケット": {"romaji":["buranketto"],"meaning":"blanket"},
    "スリッパ": {"romaji":["surippa"],"meaning":"slippers"},
    "ライト": {"romaji":["raito"],"meaning":"light"},
    "ランプ": {"romaji":["ranpu"],"meaning":"lamp"},
    "ポロシャツ": {"romaji":["poroshatsu"],"meaning":"polo shirt"},
    "ブラウス": {"romaji":["burausu"],"meaning":"blouse"},
    "ジーンズ": {"romaji":["jiinzu"],"meaning":"jeans"},
    "ショーツ": {"romaji":["shootsu"],"meaning":"shorts"},
    "パジャマ": {"romaji":["pajama"],"meaning":"pyjamas"},
    "パーカー": {"romaji":["paakaa"],"meaning":"hoodie"},
    "カーディガン": {"romaji":["kaadigan"],"meaning":"cardigan"},
    "ダウンジャケット": {"romaji":["daunjaketto"],"meaning":"down jacket"},
    "レインコート": {"romaji":["reinkooto"],"meaning":"raincoat"},
    "スーツ": {"romaji":["suutsu"],"meaning":"suit"},
    "ユニフォーム": {"romaji":["yunifoomu"],"meaning":"uniform"},
    "ヒール": {"romaji":["hiiru"],"meaning":"heels"},
    "ソックス": {"romaji":["sokkusu"],"meaning":"socks"},
    "ストッキング": {"romaji":["sutokkingu"],"meaning":"stockings"},
    "ピアス": {"romaji":["piasu"],"meaning":"earrings"},
    "ネックレス": {"romaji":["nekkuresu"],"meaning":"necklace"},
    "ブレスレット": {"romaji":["buresuretto"],"meaning":"bracelet"},
    "サングラス": {"romaji":["sangurasu"],"meaning":"sunglasses"},
    "マンション": {"romaji":["manshon"],"meaning":"apartment building"},
    "オフィス": {"romaji":["ofisu"],"meaning":"office"},
    "ジム": {"romaji":["jimu"],"meaning":"gym"},
    "カフェ": {"romaji":["kafe"],"meaning":"cafe"},
    "バー": {"romaji":["baa"],"meaning":"bar"},
    "クラブ": {"romaji":["kurabu"],"meaning":"club"},
    "シアター": {"romaji":["shiataa"],"meaning":"theatre"},
    "シネマ": {"romaji":["shinema"],"meaning":"cinema"},
    "ミュージアム": {"romaji":["myuujiamu"],"meaning":"museum"},
    "ギャラリー": {"romaji":["gyararii"],"meaning":"gallery"},
    "スタジアム": {"romaji":["sutajiamu"],"meaning":"stadium"},
    "パーク": {"romaji":["paaku"],"meaning":"park"},
    "ビーチ": {"romaji":["biichi"],"meaning":"beach"},
    "マーケット": {"romaji":["maaketto"],"meaning":"market"},
    "モール": {"romaji":["mooru"],"meaning":"mall"},
    "パーキング": {"romaji":["paakingu"],"meaning":"parking"},
    "ステーション": {"romaji":["suteeshon"],"meaning":"station"},
    "エアポート": {"romaji":["eapooto"],"meaning":"airport"},
    "ハーバー": {"romaji":["haabaa"],"meaning":"harbour"},
    "ファストフード": {"romaji":["fasutofuudo"],"meaning":"fast food place"},
    "バイク": {"romaji":["baiku"],"meaning":"motorbike"},
    "スクーターバイク": {"romaji":["sukuutaabaiku"],"meaning":"scooter"},
    "トレイン": {"romaji":["torein"],"meaning":"train"},
    "モノレール": {"romaji":["monoreeru"],"meaning":"monorail"},
    "シップ": {"romaji":["shippu"],"meaning":"ship"},
    "ヨット": {"romaji":["yotto"],"meaning":"yacht"},
    "ボート": {"romaji":["booto"],"meaning":"boat"},
    "カヌー": {"romaji":["kanuu"],"meaning":"canoe"},
    "エアプレイン": {"romaji":["eapurein"],"meaning":"airplane"},
    "ジェット": {"romaji":["jetto"],"meaning":"jet"},
    "バン": {"romaji":["ban"],"meaning":"van"},
    "ワゴン": {"romaji":["wagon"],"meaning":"wagon car"},
    "キャンピングカー": {"romaji":["kyanpingukaa"],"meaning":"camping car, RV"},
    "ガソリン": {"romaji":["gasorin"],"meaning":"gasoline"},
    "タイヤ": {"romaji":["taiya"],"meaning":"tyre"},
    "ハンドル": {"romaji":["handoru"],"meaning":"steering wheel"},
    "ブレーキ": {"romaji":["bureeki"],"meaning":"brake"},
    "シートベルト": {"romaji":["shiitoberuto"],"meaning":"seatbelt"},
    "バスケットボール": {"romaji":["basukettobooru"],"meaning":"basketball"},
    "バレーボール": {"romaji":["bareebooru"],"meaning":"volleyball"},
    "ベースボール": {"romaji":["beesubooru"],"meaning":"baseball"},
    "ラグビー": {"romaji":["ragubii"],"meaning":"rugby"},
    "ボクシング": {"romaji":["bokushingu"],"meaning":"boxing"},
    "マラソン": {"romaji":["marason"],"meaning":"marathon"},
    "スケート": {"romaji":["sukeeto"],"meaning":"skating"},
    "スノーボード": {"romaji":["sunoobooddo"],"meaning":"snowboard"},
    "サーフィン": {"romaji":["saafin"],"meaning":"surfing"},
    "ヨガ": {"romaji":["yoga"],"meaning":"yoga"},
    "フィットネス": {"romaji":["fittonesu"],"meaning":"fitness"},
    "バレエ": {"romaji":["baree"],"meaning":"ballet"},
    "バイオリン": {"romaji":["baiorin"],"meaning":"violin"},
    "フルート": {"romaji":["furuuto"],"meaning":"flute"},
    "トランペット": {"romaji":["toranpetto"],"meaning":"trumpet"},
    "サックス": {"romaji":["sakkusu"],"meaning":"saxophone"},
    "チェロ": {"romaji":["chero"],"meaning":"cello"},
    "オーケストラ": {"romaji":["ookesutora"],"meaning":"orchestra"},
    "コンサート": {"romaji":["konsaato"],"meaning":"concert"},
    "ライブ": {"romaji":["raibu"],"meaning":"live performance"},
    "ロック": {"romaji":["rokku"],"meaning":"rock (music)"},
    "ポップス": {"romaji":["poppusu"],"meaning":"pop music"},
    "クラシック": {"romaji":["kurashikku"],"meaning":"classical music"},
    "チャイナ": {"romaji":["chaina"],"meaning":"China"},
    "コリア": {"romaji":["koria"],"meaning":"Korea"},
    "インド": {"romaji":["indo"],"meaning":"India"},
    "タイ": {"romaji":["tai"],"meaning":"Thailand"},
    "ベトナム": {"romaji":["betonamu"],"meaning":"Vietnam"},
    "フィリピン": {"romaji":["firipin"],"meaning":"Philippines"},
    "インドネシア": {"romaji":["indoneshia"],"meaning":"Indonesia"},
    "シンガポール": {"romaji":["shingapooru"],"meaning":"Singapore"},
    "マレーシア": {"romaji":["mareeshia"],"meaning":"Malaysia"},
    "ブラジル": {"romaji":["burajiru"],"meaning":"Brazil"},
    "メキシコ": {"romaji":["mekishiko"],"meaning":"Mexico"},
    "アルゼンチン": {"romaji":["aruzenchin"],"meaning":"Argentina"},
    "エジプト": {"romaji":["ejiputo"],"meaning":"Egypt"},
    "ケニア": {"romaji":["kenia"],"meaning":"Kenya"},
    "トルコ": {"romaji":["toruko"],"meaning":"Turkey"},
    "ギリシャ": {"romaji":["girisha"],"meaning":"Greece"},
    "スイス": {"romaji":["suisu"],"meaning":"Switzerland"},
    "オランダ": {"romaji":["oranda"],"meaning":"Netherlands"},
    "ベルギー": {"romaji":["berugii"],"meaning":"Belgium"},
    "ポルトガル": {"romaji":["porutogaru"],"meaning":"Portugal"},
    "スウェーデン": {"romaji":["suweeden"],"meaning":"Sweden"},
    "ノルウェー": {"romaji":["noruwee"],"meaning":"Norway"},
    "フィンランド": {"romaji":["finrando"],"meaning":"Finland"},
    "アフリカ": {"romaji":["afurika"],"meaning":"Africa"},
    "プロデューサー": {"romaji":["purodyuusaa"],"meaning":"producer"},
    "ディレクター": {"romaji":["direkutaa"],"meaning":"director"},
    "エディター": {"romaji":["editaa"],"meaning":"editor"},
    "カメラマン": {"romaji":["kameraman"],"meaning":"cameraman"},
    "アナウンサー": {"romaji":["anaunsaa"],"meaning":"announcer"},
    "レポーター": {"romaji":["repootaa"],"meaning":"reporter"},
    "ライター": {"romaji":["raitaa"],"meaning":"writer"},
    "ミュージシャン": {"romaji":["myuujishan"],"meaning":"musician"},
    "シンガー": {"romaji":["shingaa"],"meaning":"singer"},
    "ダンサー": {"romaji":["dansaa"],"meaning":"dancer"},
    "アクター": {"romaji":["akutaa"],"meaning":"actor"},
    "コック": {"romaji":["kokku"],"meaning":"cook"},
    "パティシエ": {"romaji":["patishie"],"meaning":"pastry chef"},
    "バリスタ": {"romaji":["barisuta"],"meaning":"barista"},
    "ウェイター": {"romaji":["weitaa"],"meaning":"waiter"},
    "ウェイトレス": {"romaji":["weitoresu"],"meaning":"waitress"},
    "トレーナー": {"romaji":["toreenaa"],"meaning":"trainer"},
    "コーチ": {"romaji":["koochi"],"meaning":"coach"},
    "セラピスト": {"romaji":["serapisuto"],"meaning":"therapist"},
    "コンサルタント": {"romaji":["konsarutanto"],"meaning":"consultant"},
    "プラン": {"romaji":["puran"],"meaning":"plan"},
    "アイデア": {"romaji":["aidea"],"meaning":"idea"},
    "イメージ": {"romaji":["imeeji"],"meaning":"image"},
    "スタイル": {"romaji":["sutairu"],"meaning":"style"},
    "トレンド": {"romaji":["torendo"],"meaning":"trend"},
    "ブランド": {"romaji":["burando"],"meaning":"brand"},
    "ロゴ": {"romaji":["rogo"],"meaning":"logo"},
    "ポスター": {"romaji":["posutaa"],"meaning":"poster"},
    "バナー": {"romaji":["banaa"],"meaning":"banner"},
    "パーティー": {"romaji":["paatii"],"meaning":"party"},
    "イベント": {"romaji":["ibento"],"meaning":"event"},
    "ゲーム": {"romaji":["geemu"],"meaning":"game"},
    "パズル": {"romaji":["pazuru"],"meaning":"puzzle"},
    "クイズ": {"romaji":["kuizu"],"meaning":"quiz"},
    "クリスマス": {"romaji":["kurisumasu"],"meaning":"Christmas"},
    "ハロウィン": {"romaji":["harowin"],"meaning":"Halloween"},
    "バレンタイン": {"romaji":["barentain"],"meaning":"Valentine"},
    "エネルギー": {"romaji":["enerugii"],"meaning":"energy"},
    "ストレス": {"romaji":["sutoresu"],"meaning":"stress"},
    "リラックス": {"romaji":["rirakkusu"],"meaning":"relax"},
    "ムービー": {"romaji":["muubii"],"meaning":"movie"},
    "ドラマ": {"romaji":["dorama"],"meaning":"drama, TV series"},
    "アニメ": {"romaji":["anime"],"meaning":"anime"},
    "マンガ": {"romaji":["manga"],"meaning":"manga (also written まんが)"},
    "コメディ": {"romaji":["komedi"],"meaning":"comedy"},
    "ホラー": {"romaji":["horaa"],"meaning":"horror"},
    "アクション": {"romaji":["akushon"],"meaning":"action"},
    "ロマンス": {"romaji":["romansu"],"meaning":"romance"},
    "ファンタジー": {"romaji":["fantajii"],"meaning":"fantasy"},
    "ドキュメンタリー": {"romaji":["dokyumentarii"],"meaning":"documentary"},
    "シリーズ": {"romaji":["shiriizu"],"meaning":"series"},
    "エピソード": {"romaji":["episoodo"],"meaning":"episode"},
    "シーン": {"romaji":["shiin"],"meaning":"scene"},
    "キャラクター": {"romaji":["kyarakutaa"],"meaning":"character"},
    "ストーリー": {"romaji":["sutoorii"],"meaning":"story"},
    "ヒーロー": {"romaji":["hiiroo"],"meaning":"hero"},
    "ヒロイン": {"romaji":["hiroin"],"meaning":"heroine"},
    "ヴィラン": {"romaji":["viran"],"meaning":"villain"},
    "スター": {"romaji":["sutaa"],"meaning":"star, celebrity"},
    "ファン": {"romaji":["fan"],"meaning":"fan"},
    "ネット": {"romaji":["netto"],"meaning":"internet"},
    "ウェブ": {"romaji":["webu"],"meaning":"web"},
    "サイト": {"romaji":["saito"],"meaning":"site"},
    "ブログ": {"romaji":["burogu"],"meaning":"blog"},
    "フォーラム": {"romaji":["fooramu"],"meaning":"forum"},
    "チャット": {"romaji":["chatto"],"meaning":"chat"},
    "メッセンジャー": {"romaji":["messenjaa"],"meaning":"messenger"},
    "ソーシャル": {"romaji":["soosharu"],"meaning":"social"},
    "メディア": {"romaji":["media"],"meaning":"media"},
    "フォロー": {"romaji":["foroo"],"meaning":"follow"},
    "フォロワー": {"romaji":["forowaa"],"meaning":"follower"},
    "ライク": {"romaji":["raiku"],"meaning":"like"},
    "コメント": {"romaji":["komento"],"meaning":"comment"},
    "シェア": {"romaji":["shea"],"meaning":"share"},
    "アップロード": {"romaji":["appuroodo"],"meaning":"upload"},
    "ダウンロード": {"romaji":["daunroodo"],"meaning":"download"},
    "リンク": {"romaji":["rinku"],"meaning":"link"},
    "クリック": {"romaji":["kurikku"],"meaning":"click"},
    "ログイン": {"romaji":["roguin"],"meaning":"login"},
    "アカウント": {"romaji":["akaunto"],"meaning":"account"},
    "プロフィール": {"romaji":["purofiiru"],"meaning":"profile"},
    "ユーザー": {"romaji":["yuuzaa"],"meaning":"user"},
    "ツアー": {"romaji":["tsuaa"],"meaning":"tour"},
    "トリップ": {"romaji":["torippu"],"meaning":"trip"},
    "バケーション": {"romaji":["bakeeshon"],"meaning":"vacation"},
    "ホリデー": {"romaji":["horidee"],"meaning":"holiday"},
    "パスポート": {"romaji":["pasupooto"],"meaning":"passport"},
    "ビザ": {"romaji":["biza"],"meaning":"visa"},
    "スーツケース": {"romaji":["suutsukeesu"],"meaning":"suitcase"},
    "バックパック": {"romaji":["bakkupakku"],"meaning":"backpack"},
    "マップ": {"romaji":["mappu"],"meaning":"map"},
    "ガイド": {"romaji":["gaido"],"meaning":"guide"},
    "ツーリスト": {"romaji":["tsuurisuto"],"meaning":"tourist"},
    "フライト": {"romaji":["furaito"],"meaning":"flight"},
    "チェックイン": {"romaji":["chekkuin"],"meaning":"check-in"},
    "チェックアウト": {"romaji":["chekkuauto"],"meaning":"check-out"},
    "ラウンジ": {"romaji":["raunji"],"meaning":"lounge"},
    "リゾート": {"romaji":["rizooto"],"meaning":"resort"},
    "キャンプ": {"romaji":["kyanpu"],"meaning":"camp"},
    "ハイキング": {"romaji":["haikingu"],"meaning":"hiking"},
    "ピクニック": {"romaji":["pikunikku"],"meaning":"picnic"},
    "ミーティング": {"romaji":["miitingu"],"meaning":"meeting"},
    "プレゼン": {"romaji":["purezen"],"meaning":"presentation"},
    "プロジェクト": {"romaji":["purojekuto"],"meaning":"project"},
    "チーム": {"romaji":["chiimu"],"meaning":"team"},
    "スタッフ": {"romaji":["sutaffu"],"meaning":"staff"},
    "ボス": {"romaji":["bosu"],"meaning":"boss"},
    "クライアント": {"romaji":["kuraianto"],"meaning":"client"},
    "マーケティング": {"romaji":["maaketingu"],"meaning":"marketing"},
    "セールス": {"romaji":["seerusu"],"meaning":"sales"},
    "ビジネス": {"romaji":["bijinesu"],"meaning":"business"},
    "マネー": {"romaji":["manee"],"meaning":"money"},
    "キャッシュ": {"romaji":["kyasshu"],"meaning":"cash"},
    "クレジットカード": {"romaji":["kurejittokaado"],"meaning":"credit card"},
    "レシート": {"romaji":["reshiito"],"meaning":"receipt"},
    "バーゲン": {"romaji":["baagen"],"meaning":"bargain, sale"},
    "セール": {"romaji":["seeru"],"meaning":"sale"},
    "ディスカウント": {"romaji":["disukaunto"],"meaning":"discount"},
    "プライス": {"romaji":["puraisu"],"meaning":"price"},
    "ショッピング": {"romaji":["shoppingu"],"meaning":"shopping"},
    "カート": {"romaji":["kaato"],"meaning":"cart"},
    "レジ": {"romaji":["reji"],"meaning":"cash register"},
    "レッド": {"romaji":["reddo"],"meaning":"red"},
    "ブルー": {"romaji":["buruu"],"meaning":"blue"},
    "グリーン": {"romaji":["guriin"],"meaning":"green"},
    "イエロー": {"romaji":["ieroo"],"meaning":"yellow"},
    "ブラック": {"romaji":["burakku"],"meaning":"black"},
    "ホワイト": {"romaji":["howaito"],"meaning":"white"},
    "グレー": {"romaji":["guree"],"meaning":"grey"},
    "ブラウン": {"romaji":["buraun"],"meaning":"brown"},
    "ピンク": {"romaji":["pinku"],"meaning":"pink"},
    "パープル": {"romaji":["paapuru"],"meaning":"purple"},
    "ゴールド": {"romaji":["goorudo"],"meaning":"gold"},
    "シルバー": {"romaji":["shirubaa"],"meaning":"silver"},
    "ベージュ": {"romaji":["beeju"],"meaning":"beige"},
    "ネイビー": {"romaji":["neibii"],"meaning":"navy blue"},
    "パンダ": {"romaji":["panda"],"meaning":"panda"},
    "コアラ": {"romaji":["koara"],"meaning":"koala"},
    "カンガルー": {"romaji":["kangaruu"],"meaning":"kangaroo"},
    "ペンギン": {"romaji":["pengin"],"meaning":"penguin"},
    "ライオン": {"romaji":["raion"],"meaning":"lion"},
    "タイガー": {"romaji":["taigaa"],"meaning":"tiger"},
    "エレファント": {"romaji":["erefanto"],"meaning":"elephant"},
    "ジラフ": {"romaji":["jirafu"],"meaning":"giraffe"},
    "シマウマ": {"romaji":["shimauma"],"meaning":"zebra"},
    "カバ": {"romaji":["kaba"],"meaning":"hippopotamus"},
    "サイ": {"romaji":["sai"],"meaning":"rhinoceros"},
    "チーター": {"romaji":["chiitaa"],"meaning":"cheetah"},
    "ゴリラ": {"romaji":["gorira"],"meaning":"gorilla"},
    "チンパンジー": {"romaji":["chinpanjii"],"meaning":"chimpanzee"},
    "イルカ": {"romaji":["iruka"],"meaning":"dolphin"},
    "シャチ": {"romaji":["shachi"],"meaning":"orca"},
    "サメ": {"romaji":["same"],"meaning":"shark"},
    "ハムスター": {"romaji":["hamusutaa"],"meaning":"hamster"},
    "ワニ": {"romaji":["wani"],"meaning":"crocodile"},
    "フラミンゴ": {"romaji":["furamingo"],"meaning":"flamingo"}
  
  }
};

const KATAKANA_VOCAB_DATA_SUBCATEGORIES = {
    "TECHNOLOGY & GADGETS": {
        "カメラ": {"romaji":["kamera"],"meaning":"camera"},
        "テレビ": {"romaji":["terebi"],"meaning":"TV"},
        "ラジオ": {"romaji":["rajio"],"meaning":"radio"},
        "パソコン": {"romaji":["pasokon"],"meaning":"PC/laptop"},
        "スマホ": {"romaji":["sumaho"],"meaning":"smartphone"},
        "エアコン": {"romaji":["eakon"],"meaning":"air conditioner"},
        "ビデオ": {"romaji":["bideo"],"meaning":"video"},
        "リモコン": {"romaji":["rimokon"],"meaning":"remote control"},
        "インターネット": {"romaji":["intaanetto"],"meaning":"internet"},
    "マイク": {"romaji":["maiku"],"meaning":"microphone"},
    "スピーカー": {"romaji":["supiikaa"],"meaning":"speaker"},
    "イヤホン": {"romaji":["iyahon"],"meaning":"earphones"},
    "ヘッドホン": {"romaji":["heddohon"],"meaning":"headphones"},
    "プリンター": {"romaji":["purintaa"],"meaning":"printer"},
    "スキャナー": {"romaji":["sukyanaa"],"meaning":"scanner"},
    "モニター": {"romaji":["monitaa"],"meaning":"monitor"},
    "キーボード": {"romaji":["kiiboodo"],"meaning":"keyboard"},
    "マウス": {"romaji":["mausu"],"meaning":"mouse (computer)"},
    "バッテリー": {"romaji":["batterii"],"meaning":"battery"},
    "チャージャー": {"romaji":["chaajaa"],"meaning":"charger"},
    "ケーブル": {"romaji":["keeburu"],"meaning":"cable"},
    "アプリ": {"romaji":["apuri"],"meaning":"app"},
    "ソフト": {"romaji":["sofuto"],"meaning":"software"},
    "データ": {"romaji":["deeta"],"meaning":"data"},
    "ファイル": {"romaji":["fairu"],"meaning":"file"},
    "メール": {"romaji":["meeru"],"meaning":"email"},
    "パスワード": {"romaji":["pasuwaado"],"meaning":"password"},
    "ロボット": {"romaji":["robotto"],"meaning":"robot"},
    "ドローン": {"romaji":["doroon"],"meaning":"drone"}
  
    },
    "FOOD & DRINK": {
        "コーヒー": {"romaji":["ko-hi-","koohi","koohii","kohi"],"meaning":"coffee"},
        "コーラ": {"romaji":["ko-ra","koora","kora"],"meaning":"cola"},
        "ビール": {"romaji":["bi-ru","biiru","biru"],"meaning":"beer"},
        "ワイン": {"romaji":["wain"],"meaning":"wine"},
        "パン": {"romaji":["pan"],"meaning":"bread"},
        "ケーキ": {"romaji":["ke-ki","keeki","keki"],"meaning":"cake"},
        "アイス": {"romaji":["aisu"],"meaning":"ice cream"},
        "サラダ": {"romaji":["sarada"],"meaning":"salad"},
        "チーズ": {"romaji":["chi-zu","chiizu","chizu"],"meaning":"cheese"},
        "パスタ": {"romaji":["pasuta"],"meaning":"pasta"},
        "メニュー": {"romaji":["menyu-","menyuu","menyu"],"meaning":"menu"},
        "ジュース": {"romaji":["ju-su","juusu","jusu"],"meaning":"juice"},
        "ハンバーグ": {"romaji":["hanba-gu"],"meaning":"hamburger steak"},
        "ピザ": {"romaji":["piza"],"meaning":"pizza"},
        "サンドイッチ": {"romaji":["sandoitchi"],"meaning":"sandwich"},
        "チョコレート": {"romaji":["chokore-to"],"meaning":"chocolate"},
        "カレー": {"romaji":["kare-"],"meaning":"curry"},
        "スープ": {"romaji":["su-pu"],"meaning":"soup"},
    "ミルク": {"romaji":["miruku"],"meaning":"milk"},
    "ティー": {"romaji":["tii"],"meaning":"tea"},
    "ミルクティー": {"romaji":["mirukutii"],"meaning":"milk tea"},
    "レモネード": {"romaji":["remoneedo"],"meaning":"lemonade"},
    "スムージー": {"romaji":["sumuujii"],"meaning":"smoothie"},
    "シェイク": {"romaji":["sheiku"],"meaning":"milkshake"},
    "カクテル": {"romaji":["kakuteru"],"meaning":"cocktail"},
    "ウイスキー": {"romaji":["uisukii"],"meaning":"whiskey"},
    "シャンパン": {"romaji":["shanpan"],"meaning":"champagne"},
    "ヨーグルト": {"romaji":["yooguruto"],"meaning":"yoghurt"},
    "バター": {"romaji":["bataa"],"meaning":"butter"},
    "ヨーグルトドリンク": {"romaji":["yoogurutodorinku"],"meaning":"yoghurt drink"},
    "トースト": {"romaji":["toosuto"],"meaning":"toast"},
    "クッキー": {"romaji":["kukkii"],"meaning":"cookie"},
    "ドーナツ": {"romaji":["doonatsu"],"meaning":"doughnut"},
    "プリン": {"romaji":["purin"],"meaning":"pudding"},
    "マフィン": {"romaji":["mafin"],"meaning":"muffin"},
    "ワッフル": {"romaji":["waffuru"],"meaning":"waffle"},
    "パンケーキ": {"romaji":["pankeeki"],"meaning":"pancake"},
    "ハンバーガー": {"romaji":["hanbaagaa"],"meaning":"hamburger"},
    "ホットドッグ": {"romaji":["hottodoggu"],"meaning":"hot dog"},
    "フライドポテト": {"romaji":["furaidopoteto"],"meaning":"french fries"},
    "スパゲッティ": {"romaji":["supagetti"],"meaning":"spaghetti"},
    "ラザニア": {"romaji":["razania"],"meaning":"lasagna"},
    "リゾット": {"romaji":["rizotto"],"meaning":"risotto"},
    "ステーキ": {"romaji":["suteeki"],"meaning":"steak"},
    "ソーセージ": {"romaji":["sooseeji"],"meaning":"sausage"},
    "ベーコン": {"romaji":["beekon"],"meaning":"bacon"},
    "ハム": {"romaji":["hamu"],"meaning":"ham"},
    "マヨネーズ": {"romaji":["mayoneezu"],"meaning":"mayonnaise"},
    "ケチャップ": {"romaji":["kechappu"],"meaning":"ketchup"},
    "ソース": {"romaji":["soosu"],"meaning":"sauce"},
    "スパイス": {"romaji":["supaisu"],"meaning":"spice"},
    "ハーブ": {"romaji":["haabu"],"meaning":"herb"}
  
    },
    "FRUITS & VEGETABLES": {
        "バナナ": {"romaji":["banana"],"meaning":"banana"},
        "オレンジ": {"romaji":["orenji"],"meaning":"orange"},
        "リンゴ": {"romaji":["ringo"],"meaning":"apple (often katakana)"},
        "メロン": {"romaji":["meron"],"meaning":"melon"},
        "パイナップル": {"romaji":["painappuru"],"meaning":"pineapple"},
        "トマト": {"romaji":["tomato"],"meaning":"tomato"},
        "キャベツ": {"romaji":["kyabetsu"],"meaning":"cabbage"},
        "レタス": {"romaji":["retasu"],"meaning":"lettuce"},
        "マンゴー": {"romaji":["mango-"],"meaning":"mango"},
        "ブドウ": {"romaji":["budou"],"meaning":"grapes"},
        "イチゴ": {"romaji":["ichigo"],"meaning":"strawberry"},
        "ブロッコリー": {"romaji":["burokori-"],"meaning":"broccoli"},
        "ニンジン": {"romaji":["ninjin"],"meaning":"carrot"},
        "タマネギ": {"romaji":["tamanegi"],"meaning":"onion"},
        "スイカ": {"romaji":["suika"],"meaning":"watermelon"},
    "キウイ": {"romaji":["kiui"],"meaning":"kiwi"},
    "グレープフルーツ": {"romaji":["gureepufuruutsu"],"meaning":"grapefruit"},
    "レモン": {"romaji":["remon"],"meaning":"lemon"},
    "ライム": {"romaji":["raimu"],"meaning":"lime"},
    "チェリー": {"romaji":["cherii"],"meaning":"cherry"},
    "ラズベリー": {"romaji":["razuberii"],"meaning":"raspberry"},
    "ブルーベリー": {"romaji":["buruuberii"],"meaning":"blueberry"},
    "ピーチ": {"romaji":["piichi"],"meaning":"peach"},
    "プラム": {"romaji":["puramu"],"meaning":"plum"},
    "ココナッツ": {"romaji":["kokonattsu"],"meaning":"coconut"},
    "アボカド": {"romaji":["abokado"],"meaning":"avocado"},
    "パパイヤ": {"romaji":["papaiya"],"meaning":"papaya"},
    "ピーマン": {"romaji":["piiman"],"meaning":"green pepper"},
    "パプリカ": {"romaji":["papurika"],"meaning":"paprika, bell pepper"},
    "マッシュルーム": {"romaji":["masshuruumu"],"meaning":"mushroom"},
    "アスパラガス": {"romaji":["asuparagasu"],"meaning":"asparagus"},
    "セロリ": {"romaji":["serori"],"meaning":"celery"},
    "パセリ": {"romaji":["paseri"],"meaning":"parsley"},
    "スパイナッチ": {"romaji":["supainacchi"],"meaning":"spinach"},
    "ズッキーニ": {"romaji":["zukkiini"],"meaning":"zucchini"}
  
    },
    "HOUSEHOLD & OBJECTS": {
        "ドア": {"romaji":["doa"],"meaning":"door"},
        "ノート": {"romaji":["no-to","nooto","noto"],"meaning":"notebook"},
        "ペン": {"romaji":["pen"],"meaning":"pen"},
        "ボールペン": {"romaji":["bo-rupen","boorupen"],"meaning":"ballpoint pen"},
        "サンダル": {"romaji":["sandaru"],"meaning":"sandals"},
        "ハンカチ": {"romaji":["hankachi"],"meaning":"handkerchief"},
        "フォーク": {"romaji":["fo-ku","fooku","foku"],"meaning":"fork"},
        "ナイフ": {"romaji":["naifu"],"meaning":"knife"},
        "スプーン": {"romaji":["supu-n","supuun","supun"],"meaning":"spoon"},
        "コップ": {"romaji":["koppu"],"meaning":"glass/cup"},
        "キッチン": {"romaji":["kitchin"],"meaning":"kitchen"},
        "ベッド": {"romaji":["beddo"],"meaning":"bed"},
        "ソファ": {"romaji":["sofa"],"meaning":"sofa"},
        "シャワー": {"romaji":["shawa-","shawaa","shawa"],"meaning":"shower"},
        "カレンダー": {"romaji":["karenda-","karendaa"],"meaning":"calendar"},
        "テーブル": {"romaji":["te-buru"],"meaning":"table"},
        "カーテン": {"romaji":["ka-ten"],"meaning":"curtain"},
        "タンス": {"romaji":["tansu"],"meaning":"chest of drawers"},
        "タオル": {"romaji":["taoru"],"meaning":"towel"},
        "ブラシ": {"romaji":["burashi"],"meaning":"brush"},
    "カップ": {"romaji":["kappu"],"meaning":"cup"},
    "マグカップ": {"romaji":["magukappu"],"meaning":"mug"},
    "プレート": {"romaji":["pureeto"],"meaning":"plate"},
    "ボウル": {"romaji":["bouru"],"meaning":"bowl"},
    "ポット": {"romaji":["potto"],"meaning":"pot, teapot"},
    "フライパン": {"romaji":["furaipan"],"meaning":"frying pan"},
    "オーブン": {"romaji":["oobun"],"meaning":"oven"},
    "トースター": {"romaji":["toosutaa"],"meaning":"toaster"},
    "ミキサー": {"romaji":["mikisaa"],"meaning":"blender"},
    "レンジ": {"romaji":["renji"],"meaning":"microwave, stove"},
    "シンク": {"romaji":["shinku"],"meaning":"sink"},
    "バスタブ": {"romaji":["basutabu"],"meaning":"bathtub"},
    "シャンプー": {"romaji":["shanpuu"],"meaning":"shampoo"},
    "リンス": {"romaji":["rinsu"],"meaning":"conditioner"},
    "ソープ": {"romaji":["soopu"],"meaning":"soap"},
    "ティッシュ": {"romaji":["tisshu"],"meaning":"tissue"},
    "トイレットペーパー": {"romaji":["toirettopeepaa"],"meaning":"toilet paper"},
    "ゴミ": {"romaji":["gomi"],"meaning":"garbage"},
    "バケツ": {"romaji":["baketsu"],"meaning":"bucket"},
    "ハンガー": {"romaji":["hangaa"],"meaning":"hanger"},
    "クッション": {"romaji":["kusshon"],"meaning":"cushion"},
    "ブランケット": {"romaji":["buranketto"],"meaning":"blanket"},
    "スリッパ": {"romaji":["surippa"],"meaning":"slippers"},
    "ライト": {"romaji":["raito"],"meaning":"light"},
    "ランプ": {"romaji":["ranpu"],"meaning":"lamp"}
  
    },
    "CLOTHING": {
        "シャツ": {"romaji":["shatsu"],"meaning":"shirt"},
        "ズボン": {"romaji":["zubon"],"meaning":"pants"},
        "ネクタイ": {"romaji":["nekutai"],"meaning":"necktie"},
        "スカート": {"romaji":["suka-to"],"meaning":"skirt"},
        "コート": {"romaji":["ko-to"],"meaning":"coat"},
        "セーター": {"romaji":["se-ta-"],"meaning":"sweater"},
        "ドレス": {"romaji":["doresu"],"meaning":"dress"},
        "ワンピース": {"romaji":["wanpi-su"],"meaning":"one-piece dress"},
        "ジャケット": {"romaji":["jaketto"],"meaning":"jacket"},
        "ブーツ": {"romaji":["bu-tsu"],"meaning":"boots"},
        "スニーカー": {"romaji":["suni-ka-"],"meaning":"sneakers"},
        "マフラー": {"romaji":["mafura-"],"meaning":"scarf"},
        "グローブ": {"romaji":["guro-bu"],"meaning":"gloves"},
        "ベルト": {"romaji":["beruto"],"meaning":"belt"},
        "キャップ": {"romaji":["kyappu"],"meaning":"cap"},
    "ポロシャツ": {"romaji":["poroshatsu"],"meaning":"polo shirt"},
    "ブラウス": {"romaji":["burausu"],"meaning":"blouse"},
    "ジーンズ": {"romaji":["jiinzu"],"meaning":"jeans"},
    "ショーツ": {"romaji":["shootsu"],"meaning":"shorts"},
    "パジャマ": {"romaji":["pajama"],"meaning":"pyjamas"},
    "パーカー": {"romaji":["paakaa"],"meaning":"hoodie"},
    "カーディガン": {"romaji":["kaadigan"],"meaning":"cardigan"},
    "ダウンジャケット": {"romaji":["daunjaketto"],"meaning":"down jacket"},
    "レインコート": {"romaji":["reinkooto"],"meaning":"raincoat"},
    "スーツ": {"romaji":["suutsu"],"meaning":"suit"},
    "ユニフォーム": {"romaji":["yunifoomu"],"meaning":"uniform"},
    "ヒール": {"romaji":["hiiru"],"meaning":"heels"},
    "ソックス": {"romaji":["sokkusu"],"meaning":"socks"},
    "ストッキング": {"romaji":["sutokkingu"],"meaning":"stockings"},
    "ピアス": {"romaji":["piasu"],"meaning":"earrings"},
    "ネックレス": {"romaji":["nekkuresu"],"meaning":"necklace"},
    "ブレスレット": {"romaji":["buresuretto"],"meaning":"bracelet"},
    "サングラス": {"romaji":["sangurasu"],"meaning":"sunglasses"}
  
    },
    "PLACES & BUILDINGS": {
        "ホテル": {"romaji":["hoteru"],"meaning":"hotel"},
        "トイレ": {"romaji":["toire"],"meaning":"toilet/bathroom"},
        "ビル": {"romaji":["biru"],"meaning":"building"},
        "レストラン": {"romaji":["resutoran"],"meaning":"restaurant"},
        "デパート": {"romaji":["depa-to","depaato","depato"],"meaning":"department store"},
        "エレベーター": {"romaji":["erebe-ta-","erebeetaa"],"meaning":"elevator"},
        "スーパー": {"romaji":["su-pa-"],"meaning":"supermarket"},
        "コンビニ": {"romaji":["konbini"],"meaning":"convenience store"},
        "プール": {"romaji":["pu-ru"],"meaning":"pool"},
        "アパート": {"romaji":["apa-to"],"meaning":"apartment"},
    "マンション": {"romaji":["manshon"],"meaning":"apartment building"},
    "オフィス": {"romaji":["ofisu"],"meaning":"office"},
    "ジム": {"romaji":["jimu"],"meaning":"gym"},
    "カフェ": {"romaji":["kafe"],"meaning":"cafe"},
    "バー": {"romaji":["baa"],"meaning":"bar"},
    "クラブ": {"romaji":["kurabu"],"meaning":"club"},
    "シアター": {"romaji":["shiataa"],"meaning":"theatre"},
    "シネマ": {"romaji":["shinema"],"meaning":"cinema"},
    "ミュージアム": {"romaji":["myuujiamu"],"meaning":"museum"},
    "ギャラリー": {"romaji":["gyararii"],"meaning":"gallery"},
    "スタジアム": {"romaji":["sutajiamu"],"meaning":"stadium"},
    "パーク": {"romaji":["paaku"],"meaning":"park"},
    "ビーチ": {"romaji":["biichi"],"meaning":"beach"},
    "マーケット": {"romaji":["maaketto"],"meaning":"market"},
    "モール": {"romaji":["mooru"],"meaning":"mall"},
    "パーキング": {"romaji":["paakingu"],"meaning":"parking"},
    "ステーション": {"romaji":["suteeshon"],"meaning":"station"},
    "エアポート": {"romaji":["eapooto"],"meaning":"airport"},
    "ハーバー": {"romaji":["haabaa"],"meaning":"harbour"},
    "ファストフード": {"romaji":["fasutofuudo"],"meaning":"fast food place"}
  
    },
    "TRANSPORTATION": {
        "タクシー": {"romaji":["takushi-","takushii","takushi"],"meaning":"taxi"},
        "バス": {"romaji":["basu"],"meaning":"bus"},
        "トラック": {"romaji":["torakku"],"meaning":"truck"},
        "オートバイ": {"romaji":["ootobai"],"meaning":"motorcycle"},
        "エンジン": {"romaji":["enjin"],"meaning":"engine"},
        "カー": {"romaji":["ka-","kaa"],"meaning":"car"},
        "ヘリコプター": {"romaji":["herikoputa-"],"meaning":"helicopter"},
        "フェリー": {"romaji":["feri-"],"meaning":"ferry"},
        "スクーター": {"romaji":["suku-ta-"],"meaning":"scooter"},
        "リムジン": {"romaji":["rimujin"],"meaning":"limousine"},
        "ロケット": {"romaji":["roketto"],"meaning":"rocket"},
        "タンカー": {"romaji":["tanka-"],"meaning":"tanker"},
    "バイク": {"romaji":["baiku"],"meaning":"motorbike"},
    "スクーターバイク": {"romaji":["sukuutaabaiku"],"meaning":"scooter"},
    "トレイン": {"romaji":["torein"],"meaning":"train"},
    "モノレール": {"romaji":["monoreeru"],"meaning":"monorail"},
    "シップ": {"romaji":["shippu"],"meaning":"ship"},
    "ヨット": {"romaji":["yotto"],"meaning":"yacht"},
    "ボート": {"romaji":["booto"],"meaning":"boat"},
    "カヌー": {"romaji":["kanuu"],"meaning":"canoe"},
    "エアプレイン": {"romaji":["eapurein"],"meaning":"airplane"},
    "ジェット": {"romaji":["jetto"],"meaning":"jet"},
    "バン": {"romaji":["ban"],"meaning":"van"},
    "ワゴン": {"romaji":["wagon"],"meaning":"wagon car"},
    "キャンピングカー": {"romaji":["kyanpingukaa"],"meaning":"camping car, RV"},
    "ガソリン": {"romaji":["gasorin"],"meaning":"gasoline"},
    "タイヤ": {"romaji":["taiya"],"meaning":"tyre"},
    "ハンドル": {"romaji":["handoru"],"meaning":"steering wheel"},
    "ブレーキ": {"romaji":["bureeki"],"meaning":"brake"},
    "シートベルト": {"romaji":["shiitoberuto"],"meaning":"seatbelt"}
  
    },
    "SPORTS & ARTS": {
        "テニス": {"romaji":["tenisu"],"meaning":"tennis"},
        "サッカー": {"romaji":["sakka-","sakkaa","sakka"],"meaning":"soccer"},
        "ピアノ": {"romaji":["piano"],"meaning":"piano"},
        "ギター": {"romaji":["gita-","gitaa","gita"],"meaning":"guitar"},
        "スポーツ": {"romaji":["supo-tsu","supootsu"],"meaning":"sports"},
        "ダンス": {"romaji":["dansu"],"meaning":"dance"},
        "ドラム": {"romaji":["doramu"],"meaning":"drums"},
        "ゴルフ": {"romaji":["gorufu"],"meaning":"golf"},
        "スキー": {"romaji":["suki-"],"meaning":"skiing"},
        "ジャズ": {"romaji":["jazu"],"meaning":"jazz"},
    "バスケットボール": {"romaji":["basukettobooru"],"meaning":"basketball"},
    "バレーボール": {"romaji":["bareebooru"],"meaning":"volleyball"},
    "ベースボール": {"romaji":["beesubooru"],"meaning":"baseball"},
    "ラグビー": {"romaji":["ragubii"],"meaning":"rugby"},
    "ボクシング": {"romaji":["bokushingu"],"meaning":"boxing"},
    "マラソン": {"romaji":["marason"],"meaning":"marathon"},
    "スケート": {"romaji":["sukeeto"],"meaning":"skating"},
    "スノーボード": {"romaji":["sunoobooddo"],"meaning":"snowboard"},
    "サーフィン": {"romaji":["saafin"],"meaning":"surfing"},
    "ヨガ": {"romaji":["yoga"],"meaning":"yoga"},
    "フィットネス": {"romaji":["fittonesu"],"meaning":"fitness"},
    "バレエ": {"romaji":["baree"],"meaning":"ballet"},
    "バイオリン": {"romaji":["baiorin"],"meaning":"violin"},
    "フルート": {"romaji":["furuuto"],"meaning":"flute"},
    "トランペット": {"romaji":["toranpetto"],"meaning":"trumpet"},
    "サックス": {"romaji":["sakkusu"],"meaning":"saxophone"},
    "チェロ": {"romaji":["chero"],"meaning":"cello"},
    "オーケストラ": {"romaji":["ookesutora"],"meaning":"orchestra"},
    "コンサート": {"romaji":["konsaato"],"meaning":"concert"},
    "ライブ": {"romaji":["raibu"],"meaning":"live performance"},
    "ロック": {"romaji":["rokku"],"meaning":"rock (music)"},
    "ポップス": {"romaji":["poppusu"],"meaning":"pop music"},
    "クラシック": {"romaji":["kurashikku"],"meaning":"classical music"}
  
    },
    "COUNTRIES & REGIONS": {
        "アメリカ": {"romaji":["amerika"],"meaning":"USA"},
        "イギリス": {"romaji":["igirisu"],"meaning":"UK"},
        "フランス": {"romaji":["furansu"],"meaning":"France"},
        "ドイツ": {"romaji":["doitsu"],"meaning":"Germany"},
        "イタリア": {"romaji":["itaria"],"meaning":"Italy"},
        "スペイン": {"romaji":["supein"],"meaning":"Spain"},
        "カナダ": {"romaji":["kanada"],"meaning":"Canada"},
        "オーストラリア": {"romaji":["oosutoraria"],"meaning":"Australia"},
        "ロシア": {"romaji":["roshia"],"meaning":"Russia"},
        "アジア": {"romaji":["ajia"],"meaning":"Asia"},
        "ヨーロッパ": {"romaji":["yo-roppa"],"meaning":"Europe"},
    "チャイナ": {"romaji":["chaina"],"meaning":"China"},
    "コリア": {"romaji":["koria"],"meaning":"Korea"},
    "インド": {"romaji":["indo"],"meaning":"India"},
    "タイ": {"romaji":["tai"],"meaning":"Thailand"},
    "ベトナム": {"romaji":["betonamu"],"meaning":"Vietnam"},
    "フィリピン": {"romaji":["firipin"],"meaning":"Philippines"},
    "インドネシア": {"romaji":["indoneshia"],"meaning":"Indonesia"},
    "シンガポール": {"romaji":["shingapooru"],"meaning":"Singapore"},
    "マレーシア": {"romaji":["mareeshia"],"meaning":"Malaysia"},
    "ブラジル": {"romaji":["burajiru"],"meaning":"Brazil"},
    "メキシコ": {"romaji":["mekishiko"],"meaning":"Mexico"},
    "アルゼンチン": {"romaji":["aruzenchin"],"meaning":"Argentina"},
    "エジプト": {"romaji":["ejiputo"],"meaning":"Egypt"},
    "ケニア": {"romaji":["kenia"],"meaning":"Kenya"},
    "トルコ": {"romaji":["toruko"],"meaning":"Turkey"},
    "ギリシャ": {"romaji":["girisha"],"meaning":"Greece"},
    "スイス": {"romaji":["suisu"],"meaning":"Switzerland"},
    "オランダ": {"romaji":["oranda"],"meaning":"Netherlands"},
    "ベルギー": {"romaji":["berugii"],"meaning":"Belgium"},
    "ポルトガル": {"romaji":["porutogaru"],"meaning":"Portugal"},
    "スウェーデン": {"romaji":["suweeden"],"meaning":"Sweden"},
    "ノルウェー": {"romaji":["noruwee"],"meaning":"Norway"},
    "フィンランド": {"romaji":["finrando"],"meaning":"Finland"},
    "アフリカ": {"romaji":["afurika"],"meaning":"Africa"}
  
    },
    "OCCUPATIONS": {
        "エンジニア": {"romaji":["enjinia"],"meaning":"engineer"},
        "デザイナー": {"romaji":["dezaina-"],"meaning":"designer"},
        "パイロット": {"romaji":["pairotto"],"meaning":"pilot"},
        "サラリーマン": {"romaji":["sarari-man"],"meaning":"office worker"},
        "モデル": {"romaji":["moderu"],"meaning":"model"},
        "ドクター": {"romaji":["dokuta-"],"meaning":"doctor"},
        "ナース": {"romaji":["na-su"],"meaning":"nurse"},
        "シェフ": {"romaji":["shefu"],"meaning":"chef"},
        "アーティスト": {"romaji":["a-tisuto"],"meaning":"artist"},
        "ジャーナリスト": {"romaji":["ja-narisuto"],"meaning":"journalist"},
        "プログラマー": {"romaji":["purograma-"],"meaning":"programmer"},
        "マネージャー": {"romaji":["mane-ja-"],"meaning":"manager"},
    "プロデューサー": {"romaji":["purodyuusaa"],"meaning":"producer"},
    "ディレクター": {"romaji":["direkutaa"],"meaning":"director"},
    "エディター": {"romaji":["editaa"],"meaning":"editor"},
    "カメラマン": {"romaji":["kameraman"],"meaning":"cameraman"},
    "アナウンサー": {"romaji":["anaunsaa"],"meaning":"announcer"},
    "レポーター": {"romaji":["repootaa"],"meaning":"reporter"},
    "ライター": {"romaji":["raitaa"],"meaning":"writer"},
    "ミュージシャン": {"romaji":["myuujishan"],"meaning":"musician"},
    "シンガー": {"romaji":["shingaa"],"meaning":"singer"},
    "ダンサー": {"romaji":["dansaa"],"meaning":"dancer"},
    "アクター": {"romaji":["akutaa"],"meaning":"actor"},
    "コック": {"romaji":["kokku"],"meaning":"cook"},
    "パティシエ": {"romaji":["patishie"],"meaning":"pastry chef"},
    "バリスタ": {"romaji":["barisuta"],"meaning":"barista"},
    "ウェイター": {"romaji":["weitaa"],"meaning":"waiter"},
    "ウェイトレス": {"romaji":["weitoresu"],"meaning":"waitress"},
    "トレーナー": {"romaji":["toreenaa"],"meaning":"trainer"},
    "コーチ": {"romaji":["koochi"],"meaning":"coach"},
    "セラピスト": {"romaji":["serapisuto"],"meaning":"therapist"},
    "コンサルタント": {"romaji":["konsarutanto"],"meaning":"consultant"}
  
    },
    "MISC": {
        "ニュース": {"romaji":["nyu-su","nyuusu","nyusu"],"meaning":"news"},
        "プレゼント": {"romaji":["purezento"],"meaning":"present"},
        "クラス": {"romaji":["kurasu"],"meaning":"class"},
        "チケット": {"romaji":["chiketto"],"meaning":"ticket"},
        "ネコ": {"romaji":["neko"],"meaning":"cat (often katakana)"},
        "ルール": {"romaji":["ru-ru"],"meaning":"rule"},
        "チャンス": {"romaji":["chansu"],"meaning":"chance"},
        "サービス": {"romaji":["sa-bisu"],"meaning":"service"},
        "メッセージ": {"romaji":["messe-ji"],"meaning":"message"},
        "ページ": {"romaji":["pe-ji"],"meaning":"page"},
    "プラン": {"romaji":["puran"],"meaning":"plan"},
    "アイデア": {"romaji":["aidea"],"meaning":"idea"},
    "イメージ": {"romaji":["imeeji"],"meaning":"image"},
    "スタイル": {"romaji":["sutairu"],"meaning":"style"},
    "トレンド": {"romaji":["torendo"],"meaning":"trend"},
    "ブランド": {"romaji":["burando"],"meaning":"brand"},
    "ロゴ": {"romaji":["rogo"],"meaning":"logo"},
    "ポスター": {"romaji":["posutaa"],"meaning":"poster"},
    "バナー": {"romaji":["banaa"],"meaning":"banner"},
    "パーティー": {"romaji":["paatii"],"meaning":"party"},
    "イベント": {"romaji":["ibento"],"meaning":"event"},
    "ゲーム": {"romaji":["geemu"],"meaning":"game"},
    "パズル": {"romaji":["pazuru"],"meaning":"puzzle"},
    "クイズ": {"romaji":["kuizu"],"meaning":"quiz"},
    "クリスマス": {"romaji":["kurisumasu"],"meaning":"Christmas"},
    "ハロウィン": {"romaji":["harowin"],"meaning":"Halloween"},
    "バレンタイン": {"romaji":["barentain"],"meaning":"Valentine"},
    "エネルギー": {"romaji":["enerugii"],"meaning":"energy"},
    "ストレス": {"romaji":["sutoresu"],"meaning":"stress"},
    "リラックス": {"romaji":["rirakkusu"],"meaning":"relax"}
  
    },
  "ENTERTAINMENT & MEDIA": {
    "ムービー": {"romaji":["muubii"],"meaning":"movie"},
    "ドラマ": {"romaji":["dorama"],"meaning":"drama, TV series"},
    "アニメ": {"romaji":["anime"],"meaning":"anime"},
    "マンガ": {"romaji":["manga"],"meaning":"manga (also written まんが)"},
    "コメディ": {"romaji":["komedi"],"meaning":"comedy"},
    "ホラー": {"romaji":["horaa"],"meaning":"horror"},
    "アクション": {"romaji":["akushon"],"meaning":"action"},
    "ロマンス": {"romaji":["romansu"],"meaning":"romance"},
    "ファンタジー": {"romaji":["fantajii"],"meaning":"fantasy"},
    "ドキュメンタリー": {"romaji":["dokyumentarii"],"meaning":"documentary"},
    "シリーズ": {"romaji":["shiriizu"],"meaning":"series"},
    "エピソード": {"romaji":["episoodo"],"meaning":"episode"},
    "シーン": {"romaji":["shiin"],"meaning":"scene"},
    "キャラクター": {"romaji":["kyarakutaa"],"meaning":"character"},
    "ストーリー": {"romaji":["sutoorii"],"meaning":"story"},
    "ヒーロー": {"romaji":["hiiroo"],"meaning":"hero"},
    "ヒロイン": {"romaji":["hiroin"],"meaning":"heroine"},
    "ヴィラン": {"romaji":["viran"],"meaning":"villain"},
    "スター": {"romaji":["sutaa"],"meaning":"star, celebrity"},
    "ファン": {"romaji":["fan"],"meaning":"fan"}
  },
  "INTERNET & COMPUTING": {
    "ネット": {"romaji":["netto"],"meaning":"internet"},
    "ウェブ": {"romaji":["webu"],"meaning":"web"},
    "サイト": {"romaji":["saito"],"meaning":"site"},
    "ブログ": {"romaji":["burogu"],"meaning":"blog"},
    "フォーラム": {"romaji":["fooramu"],"meaning":"forum"},
    "チャット": {"romaji":["chatto"],"meaning":"chat"},
    "メッセンジャー": {"romaji":["messenjaa"],"meaning":"messenger"},
    "ソーシャル": {"romaji":["soosharu"],"meaning":"social"},
    "メディア": {"romaji":["media"],"meaning":"media"},
    "フォロー": {"romaji":["foroo"],"meaning":"follow"},
    "フォロワー": {"romaji":["forowaa"],"meaning":"follower"},
    "ライク": {"romaji":["raiku"],"meaning":"like"},
    "コメント": {"romaji":["komento"],"meaning":"comment"},
    "シェア": {"romaji":["shea"],"meaning":"share"},
    "アップロード": {"romaji":["appuroodo"],"meaning":"upload"},
    "ダウンロード": {"romaji":["daunroodo"],"meaning":"download"},
    "リンク": {"romaji":["rinku"],"meaning":"link"},
    "クリック": {"romaji":["kurikku"],"meaning":"click"},
    "ログイン": {"romaji":["roguin"],"meaning":"login"},
    "アカウント": {"romaji":["akaunto"],"meaning":"account"},
    "プロフィール": {"romaji":["purofiiru"],"meaning":"profile"},
    "ユーザー": {"romaji":["yuuzaa"],"meaning":"user"}
  },
  "TRAVEL & TOURISM": {
    "ツアー": {"romaji":["tsuaa"],"meaning":"tour"},
    "トリップ": {"romaji":["torippu"],"meaning":"trip"},
    "バケーション": {"romaji":["bakeeshon"],"meaning":"vacation"},
    "ホリデー": {"romaji":["horidee"],"meaning":"holiday"},
    "パスポート": {"romaji":["pasupooto"],"meaning":"passport"},
    "ビザ": {"romaji":["biza"],"meaning":"visa"},
    "スーツケース": {"romaji":["suutsukeesu"],"meaning":"suitcase"},
    "バックパック": {"romaji":["bakkupakku"],"meaning":"backpack"},
    "マップ": {"romaji":["mappu"],"meaning":"map"},
    "ガイド": {"romaji":["gaido"],"meaning":"guide"},
    "ツーリスト": {"romaji":["tsuurisuto"],"meaning":"tourist"},
    "フライト": {"romaji":["furaito"],"meaning":"flight"},
    "チェックイン": {"romaji":["chekkuin"],"meaning":"check-in"},
    "チェックアウト": {"romaji":["chekkuauto"],"meaning":"check-out"},
    "ラウンジ": {"romaji":["raunji"],"meaning":"lounge"},
    "リゾート": {"romaji":["rizooto"],"meaning":"resort"},
    "キャンプ": {"romaji":["kyanpu"],"meaning":"camp"},
    "ハイキング": {"romaji":["haikingu"],"meaning":"hiking"},
    "ピクニック": {"romaji":["pikunikku"],"meaning":"picnic"}
  },
  "BUSINESS & SHOPPING": {
    "ミーティング": {"romaji":["miitingu"],"meaning":"meeting"},
    "プレゼン": {"romaji":["purezen"],"meaning":"presentation"},
    "プロジェクト": {"romaji":["purojekuto"],"meaning":"project"},
    "チーム": {"romaji":["chiimu"],"meaning":"team"},
    "スタッフ": {"romaji":["sutaffu"],"meaning":"staff"},
    "ボス": {"romaji":["bosu"],"meaning":"boss"},
    "クライアント": {"romaji":["kuraianto"],"meaning":"client"},
    "マーケティング": {"romaji":["maaketingu"],"meaning":"marketing"},
    "セールス": {"romaji":["seerusu"],"meaning":"sales"},
    "ビジネス": {"romaji":["bijinesu"],"meaning":"business"},
    "マネー": {"romaji":["manee"],"meaning":"money"},
    "キャッシュ": {"romaji":["kyasshu"],"meaning":"cash"},
    "クレジットカード": {"romaji":["kurejittokaado"],"meaning":"credit card"},
    "レシート": {"romaji":["reshiito"],"meaning":"receipt"},
    "バーゲン": {"romaji":["baagen"],"meaning":"bargain, sale"},
    "セール": {"romaji":["seeru"],"meaning":"sale"},
    "ディスカウント": {"romaji":["disukaunto"],"meaning":"discount"},
    "プライス": {"romaji":["puraisu"],"meaning":"price"},
    "ショッピング": {"romaji":["shoppingu"],"meaning":"shopping"},
    "カート": {"romaji":["kaato"],"meaning":"cart"},
    "レジ": {"romaji":["reji"],"meaning":"cash register"}
  },
  "COLORS": {
    "レッド": {"romaji":["reddo"],"meaning":"red"},
    "ブルー": {"romaji":["buruu"],"meaning":"blue"},
    "グリーン": {"romaji":["guriin"],"meaning":"green"},
    "イエロー": {"romaji":["ieroo"],"meaning":"yellow"},
    "ブラック": {"romaji":["burakku"],"meaning":"black"},
    "ホワイト": {"romaji":["howaito"],"meaning":"white"},
    "グレー": {"romaji":["guree"],"meaning":"grey"},
    "ブラウン": {"romaji":["buraun"],"meaning":"brown"},
    "ピンク": {"romaji":["pinku"],"meaning":"pink"},
    "パープル": {"romaji":["paapuru"],"meaning":"purple"},
    "ゴールド": {"romaji":["goorudo"],"meaning":"gold"},
    "シルバー": {"romaji":["shirubaa"],"meaning":"silver"},
    "ベージュ": {"romaji":["beeju"],"meaning":"beige"},
    "ネイビー": {"romaji":["neibii"],"meaning":"navy blue"}
  },
  "ANIMALS": {
    "パンダ": {"romaji":["panda"],"meaning":"panda"},
    "コアラ": {"romaji":["koara"],"meaning":"koala"},
    "カンガルー": {"romaji":["kangaruu"],"meaning":"kangaroo"},
    "ペンギン": {"romaji":["pengin"],"meaning":"penguin"},
    "ライオン": {"romaji":["raion"],"meaning":"lion"},
    "タイガー": {"romaji":["taigaa"],"meaning":"tiger"},
    "エレファント": {"romaji":["erefanto"],"meaning":"elephant"},
    "ジラフ": {"romaji":["jirafu"],"meaning":"giraffe"},
    "シマウマ": {"romaji":["shimauma"],"meaning":"zebra"},
    "カバ": {"romaji":["kaba"],"meaning":"hippopotamus"},
    "サイ": {"romaji":["sai"],"meaning":"rhinoceros"},
    "チーター": {"romaji":["chiitaa"],"meaning":"cheetah"},
    "ゴリラ": {"romaji":["gorira"],"meaning":"gorilla"},
    "チンパンジー": {"romaji":["chinpanjii"],"meaning":"chimpanzee"},
    "イルカ": {"romaji":["iruka"],"meaning":"dolphin"},
    "シャチ": {"romaji":["shachi"],"meaning":"orca"},
    "サメ": {"romaji":["same"],"meaning":"shark"},
    "ハムスター": {"romaji":["hamusutaa"],"meaning":"hamster"},
    "ワニ": {"romaji":["wani"],"meaning":"crocodile"},
    "フラミンゴ": {"romaji":["furamingo"],"meaning":"flamingo"}
  }
};
